version: "3.8"

services:
    django:
        build: .
        container_name: JobBoard
        command: bash -c " python manage.py makemigrations && python manage.py migrate   && gunicorn JobApplicationSystem.wsgi:application --bind 0.0.0.0:8000 " #&& python manage.py runserver 0.0.0.0:8000"
        volumes:
            - static_volume:/app/static
            - media_volume:/app/media
        expose:
            - 8000

        #ports:
         #   - '8000:8000'
        depends_on:
            - sqlserver
    
    sqlserver:
        image: mcr.microsoft.com/mssql/server
        container_name: sqlserver
        hostname: sqlserver
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=${SQL_DB_PASS}
        ports:
            - 1433:1433
        volumes:
            - sqlserver-data:/var/opt/mssql

    nginx:
        build: ./nginx
        container_name: nginx
        volumes:
            - static_volume:/app/static
            - media_volume:/app/media
        ports:
            - 1337:80
        depends_on:
            - django


volumes:
  media_volume:
  static_volume:
  sqlserver-data:
    driver: local
            
            
          



