# Generated by Django 3.2.6 on 2022-07-04 12:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateField(auto_now_add=True)),
                ('commitment', models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12)),
                ('MSG_knowledge', models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12)),
                ('MSG_comp_knowledge', models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12)),
                ('self_exp_skill', models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12)),
                ('body_exp_skill', models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12)),
                ('behaviour', models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12)),
                ('asked_q_level', models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12)),
                ('eng_lang_skill', models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12)),
                ('computer_skill', models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12)),
                ('working_experience', models.TextField(blank=True, max_length=3000)),
                ('management_leading_cap', models.TextField(blank=True, max_length=3000)),
                ('tech_cap', models.TextField(blank=True, max_length=3000)),
                ('personality', models.TextField(blank=True, max_length=3000)),
                ('prev_work_leave', models.TextField(blank=True, max_length=3000)),
                ('achievements', models.TextField(blank=True, max_length=3000)),
                ('pros', models.TextField(blank=True, max_length=3000)),
                ('cons', models.TextField(blank=True, max_length=3000)),
                ('expected_salary', models.IntegerField(default=0, max_length=100)),
                ('work_time', models.DateTimeField(default=datetime.datetime.now)),
                ('note', models.TextField(blank=True, max_length=3000)),
                ('hiring_Recommendation', models.CharField(choices=[('Yes', 'نعم'), ('No', 'لا')], default='No', max_length=3)),
                ('interview_application', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.application')),
            ],
        ),
    ]
