# Generated by Django 3.2.6 on 2022-10-11 14:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateField(auto_now_add=True, verbose_name='تاريخ ألإنشاء')),
                ('commitment', models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12, verbose_name='ألإلتزام بموعد المقابلة')),
                ('MSG_knowledge', models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12, verbose_name='المعرفة السابقة عن الشركة')),
                ('MSG_comp_knowledge', models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12, verbose_name='المعرفة السابقة عن قطاع الشركة')),
                ('self_exp_skill', models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12, verbose_name='المهارات اللفظية بالتعبير عن نفسه')),
                ('body_exp_skill', models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12, verbose_name='مهارات التعبير والتواصل بلغة الجسد')),
                ('behaviour', models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12, verbose_name='السلوك أثناء الرد على ألأسئلة')),
                ('listening_skills', models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12, verbose_name='مهارة ألإستماع للجنة المقابلة')),
                ('asked_q_level', models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12, verbose_name='مستوى ألأسئلة المطروحة من المرشح')),
                ('eng_lang_skill', models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12, verbose_name='اللغة الانجليزية')),
                ('computer_skill', models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12, verbose_name='مهارات الحاسوب')),
                ('working_experience', models.TextField(blank=True, max_length=3000, verbose_name='الخبرة العملية')),
                ('management_leading_cap', models.TextField(blank=True, max_length=3000, verbose_name='القدرات القيادية أو الادارية')),
                ('tech_cap', models.TextField(blank=True, max_length=3000, verbose_name='القدرات الفنية')),
                ('personality', models.TextField(blank=True, max_length=3000, verbose_name='الشخصية والمظهر العام')),
                ('prev_work_leave', models.TextField(blank=True, max_length=3000, verbose_name='سبب ترك أخر عمل')),
                ('achievements', models.TextField(blank=True, max_length=3000, verbose_name='أهم ألإنجازات برأي المرشح')),
                ('pros', models.TextField(blank=True, max_length=3000, verbose_name='أبرز ألإيجابيات')),
                ('cons', models.TextField(blank=True, max_length=3000, verbose_name='أبرز السلبيات')),
                ('expected_salary', models.IntegerField(default=0, max_length=100, verbose_name='الراتب المتوقع')),
                ('work_time', models.DateField(default=datetime.datetime.now, verbose_name='أقرب وقت للإلتحاق بالعمل')),
                ('note', models.TextField(blank=True, max_length=3000, verbose_name='ملاحظات عامة')),
                ('hiring_Recommendation', models.CharField(choices=[('Pending', 'قيد الإنتظار'), ('Yes', 'نعم'), ('No', 'لا'), ('Waiting', 'قائمة الإنتظار'), ('Second_Interview', 'مقابلة ثانية ')], default='Pending', max_length=16, verbose_name='التوصية بالتعين')),
                ('HRpost_date', models.DateField(auto_now_add=True, verbose_name='تاريخ ألإنشاء')),
                ('HRcommitment', models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12, verbose_name='ألإلتزام بموعد المقابلة')),
                ('HRMSG_knowledge', models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12, verbose_name='المعرفة السابقة عن الشركة')),
                ('HRMSG_comp_knowledge', models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12, verbose_name='المعرفة السابقة عن قطاع الشركة')),
                ('HRself_exp_skill', models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12, verbose_name='المهارات اللفظية بالتعبير عن نفسه')),
                ('HRbody_exp_skill', models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12, verbose_name='مهارات التعبير والتواصل بلغة الجسد')),
                ('HRbehaviour', models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12, verbose_name='السلوك أثناء الرد على ألأسئلة')),
                ('HRlistening_skills', models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12, verbose_name='مهارة ألإستماع للجنة المقابلة')),
                ('HRasked_q_level', models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12, verbose_name='مستوى ألأسئلة المطروحة من المرشح')),
                ('HReng_lang_skill', models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12, verbose_name='اللغة الانجليزية')),
                ('HRcomputer_skill', models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12, verbose_name='مهارات الحاسوب')),
                ('HRworking_experience', models.TextField(blank=True, max_length=3000, verbose_name='الخبرة العملية')),
                ('HRmanagement_leading_cap', models.TextField(blank=True, max_length=3000, verbose_name='القدرات القيادية أو الادارية')),
                ('HRtech_cap', models.TextField(blank=True, max_length=3000, verbose_name='القدرات الفنية')),
                ('HRpersonality', models.TextField(blank=True, max_length=3000, verbose_name='الشخصية والمظهر العام')),
                ('HRprev_work_leave', models.TextField(blank=True, max_length=3000, verbose_name='سبب ترك أخر عمل')),
                ('HRachievements', models.TextField(blank=True, max_length=3000, verbose_name='أهم ألإنجازات برأي المرشح')),
                ('HRpros', models.TextField(blank=True, max_length=3000, verbose_name='أبرز ألإيجابيات')),
                ('HRcons', models.TextField(blank=True, max_length=3000, verbose_name='أبرز السلبيات')),
                ('HRnote', models.TextField(blank=True, max_length=3000, verbose_name='ملاحظات عامة')),
                ('interview_application', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.application', verbose_name='طلب التوظيف')),
            ],
            options={
                'verbose_name': 'المقابلات',
                'verbose_name_plural': 'المقابلات',
            },
        ),
    ]
