# Generated by Django 3.2.6 on 2022-06-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commitment', models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12)),
                ('MSG_knowledge', models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12)),
                ('MSG_comp_knowledge', models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12)),
                ('self_exp_skill', models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12)),
                ('body_exp_skill', models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12)),
                ('behaviour', models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12)),
                ('asked_q_level', models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12)),
                ('eng_lang_skill', models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12)),
                ('computer_skill', models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12)),
            ],
        ),
    ]
