# Generated by Django 3.2.6 on 2022-07-05 10:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20220705_1052'),
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interview',
            options={'verbose_name': 'المقابلات', 'verbose_name_plural': 'المقابلات'},
        ),
        migrations.AddField(
            model_name='interview',
            name='listening_skills',
            field=models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12, verbose_name='مهارة ألإستماع للجنة المقابلة'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='MSG_comp_knowledge',
            field=models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12, verbose_name='المعرفة السابقة عن قطاع الشركة'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='MSG_knowledge',
            field=models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12, verbose_name='المعرفة السابقة عن الشركة'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='achievements',
            field=models.TextField(blank=True, max_length=3000, verbose_name='أهم ألإنجازات برأي المرشح'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='asked_q_level',
            field=models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12, verbose_name='مستوى ألأسئلة المطروحة من المرشح'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='behaviour',
            field=models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12, verbose_name='السلوك أثناء الرد على ألأسئلة'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='body_exp_skill',
            field=models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12, verbose_name='مهارات التعبير والتواصل بلغة الجسد'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='commitment',
            field=models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12, verbose_name='ألإلتزام بموعد المقابلة'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='computer_skill',
            field=models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12, verbose_name='مهارات الحاسوب'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='cons',
            field=models.TextField(blank=True, max_length=3000, verbose_name='أبرز السلبيات'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='eng_lang_skill',
            field=models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12, verbose_name='اللغة الانجليزية'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='expected_salary',
            field=models.IntegerField(default=0, max_length=100, verbose_name='الراتب المتوقع'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='hiring_Recommendation',
            field=models.CharField(choices=[('Yes', 'نعم'), ('No', 'لا')], default='No', max_length=3, verbose_name='التوصية بالتعين'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_application',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.application', verbose_name='طلب التوظيف'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='management_leading_cap',
            field=models.TextField(blank=True, max_length=3000, verbose_name='القدرات القيادية أو الادارية'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='note',
            field=models.TextField(blank=True, max_length=3000, verbose_name='ملاحظات عامة'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='personality',
            field=models.TextField(blank=True, max_length=3000, verbose_name='الشخصية والمظهر العام'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='post_date',
            field=models.DateField(auto_now_add=True, verbose_name='تاريخ ألإنشاء'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='prev_work_leave',
            field=models.TextField(blank=True, max_length=3000, verbose_name='سبب ترك أخر عمل'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='pros',
            field=models.TextField(blank=True, max_length=3000, verbose_name='أبرز ألإيجابيات'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='self_exp_skill',
            field=models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12, verbose_name='المهارات اللفظية بالتعبير عن نفسه'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='tech_cap',
            field=models.TextField(blank=True, max_length=3000, verbose_name='القدرات الفنية'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='work_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='أقرب وقت للإلتحاق بالعمل'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='working_experience',
            field=models.TextField(blank=True, max_length=3000, verbose_name='الخبرة العملية'),
        ),
    ]
