# Generated by Django 3.2.6 on 2022-07-03 12:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_application_job_app'),
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='achievements',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='interview',
            name='cons',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='interview',
            name='expected_salary',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='interview',
            name='hiring_Recommendation',
            field=models.CharField(choices=[('Yes', 'نعم'), ('No', 'لا')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='interview',
            name='interview_application',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.application'),
        ),
        migrations.AddField(
            model_name='interview',
            name='management_leading_cap',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='interview',
            name='note',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='interview',
            name='personality',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='interview',
            name='post_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interview',
            name='prev_work_leave',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='interview',
            name='pros',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='interview',
            name='tech_cap',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='interview',
            name='work_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='interview',
            name='working_experience',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
