# Generated by Django 3.2.6 on 2022-09-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='hiring_Recommendation',
            field=models.CharField(choices=[('Yes', 'نعم'), ('No', 'لا'), ('Pending', 'قيد الإنتظار'), ('Waiting', 'قائمة الإنتظار'), ('Second_Interview', 'مقابلة ثانية ')], default='Pending', max_length=16, verbose_name='التوصية بالتعين'),
        ),
    ]
