# Generated by Django 3.2.6 on 2022-09-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_alter_interview_hiring_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='hiring_Recommendation',
            field=models.CharField(choices=[('Pending', 'قيد الإنتظار'), ('Yes', 'نعم'), ('No', 'لا'), ('Waiting', 'قائمة الإنتظار'), ('Second_Interview', 'مقابلة ثانية ')], default='Pending', max_length=16, verbose_name='التوصية بالتعين'),
        ),
    ]
