# Generated by Django 3.2.6 on 2022-09-28 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_alter_interview_hiring_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='work_time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='أقرب وقت للإلتحاق بالعمل'),
        ),
    ]
