# Generated by Django 3.2.6 on 2022-10-03 09:04

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_alter_interview_work_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='HRMSG_comp_knowledge',
            field=models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12, verbose_name='المعرفة السابقة عن قطاع الشركة'),
        ),
        migrations.AddField(
            model_name='interview',
            name='HRMSG_knowledge',
            field=models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12, verbose_name='المعرفة السابقة عن الشركة'),
        ),
        migrations.AddField(
            model_name='interview',
            name='HRachievements',
            field=models.TextField(blank=True, max_length=3000, verbose_name='أهم ألإنجازات برأي المرشح'),
        ),
        migrations.AddField(
            model_name='interview',
            name='HRasked_q_level',
            field=models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12, verbose_name='مستوى ألأسئلة المطروحة من المرشح'),
        ),
        migrations.AddField(
            model_name='interview',
            name='HRbehaviour',
            field=models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12, verbose_name='السلوك أثناء الرد على ألأسئلة'),
        ),
        migrations.AddField(
            model_name='interview',
            name='HRbody_exp_skill',
            field=models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12, verbose_name='مهارات التعبير والتواصل بلغة الجسد'),
        ),
        migrations.AddField(
            model_name='interview',
            name='HRcommitment',
            field=models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12, verbose_name='ألإلتزام بموعد المقابلة'),
        ),
        migrations.AddField(
            model_name='interview',
            name='HRcomputer_skill',
            field=models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12, verbose_name='مهارات الحاسوب'),
        ),
        migrations.AddField(
            model_name='interview',
            name='HRcons',
            field=models.TextField(blank=True, max_length=3000, verbose_name='أبرز السلبيات'),
        ),
        migrations.AddField(
            model_name='interview',
            name='HReng_lang_skill',
            field=models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12, verbose_name='اللغة الانجليزية'),
        ),
        migrations.AddField(
            model_name='interview',
            name='HRexpected_salary',
            field=models.IntegerField(default=0, max_length=100, verbose_name='الراتب المتوقع'),
        ),
        migrations.AddField(
            model_name='interview',
            name='HRhiring_Recommendation',
            field=models.CharField(choices=[('Pending', 'قيد الإنتظار'), ('Yes', 'نعم'), ('No', 'لا'), ('Waiting', 'قائمة الإنتظار'), ('Second_Interview', 'مقابلة ثانية ')], default='Pending', max_length=16, verbose_name='التوصية بالتعين'),
        ),
        migrations.AddField(
            model_name='interview',
            name='HRlistening_skills',
            field=models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12, verbose_name='مهارة ألإستماع للجنة المقابلة'),
        ),
        migrations.AddField(
            model_name='interview',
            name='HRmanagement_leading_cap',
            field=models.TextField(blank=True, max_length=3000, verbose_name='القدرات القيادية أو الادارية'),
        ),
        migrations.AddField(
            model_name='interview',
            name='HRnote',
            field=models.TextField(blank=True, max_length=3000, verbose_name='ملاحظات عامة'),
        ),
        migrations.AddField(
            model_name='interview',
            name='HRpersonality',
            field=models.TextField(blank=True, max_length=3000, verbose_name='الشخصية والمظهر العام'),
        ),
        migrations.AddField(
            model_name='interview',
            name='HRpost_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ ألإنشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interview',
            name='HRprev_work_leave',
            field=models.TextField(blank=True, max_length=3000, verbose_name='سبب ترك أخر عمل'),
        ),
        migrations.AddField(
            model_name='interview',
            name='HRpros',
            field=models.TextField(blank=True, max_length=3000, verbose_name='أبرز ألإيجابيات'),
        ),
        migrations.AddField(
            model_name='interview',
            name='HRself_exp_skill',
            field=models.CharField(choices=[('Excellent', 'ممتاز'), ('Very Good', 'جيد جدا'), ('Good', 'جيد'), ('Bad', ' غير مقبول')], default='Very Good', max_length=12, verbose_name='المهارات اللفظية بالتعبير عن نفسه'),
        ),
        migrations.AddField(
            model_name='interview',
            name='HRtech_cap',
            field=models.TextField(blank=True, max_length=3000, verbose_name='القدرات الفنية'),
        ),
        migrations.AddField(
            model_name='interview',
            name='HRwork_time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='أقرب وقت للإلتحاق بالعمل'),
        ),
        migrations.AddField(
            model_name='interview',
            name='HRworking_experience',
            field=models.TextField(blank=True, max_length=3000, verbose_name='الخبرة العملية'),
        ),
    ]
