# Generated by Django 3.2.6 on 2022-10-03 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_auto_20221003_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='HRexpected_salary',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='HRhiring_Recommendation',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='HRwork_time',
        ),
    ]
