# Generated by Django 3.2.6 on 2022-06-30 13:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NID', models.CharField(error_messages={'required': 'Please let us know what to call you!'}, max_length=10, verbose_name='الرقم الوطني')),
                ('Email', models.EmailField(max_length=100)),
                ('Birth_Date', models.DateField(default=datetime.datetime.now)),
                ('Name', models.CharField(max_length=100)),
                ('Create_Date', models.DateField(auto_now_add=True)),
                ('Socility_Status', models.CharField(choices=[('Married', 'متزوج'), ('Single', 'أعزب')], default='Single', max_length=10)),
                ('Birth_Location', models.CharField(blank=True, max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Location', models.CharField(blank=True, max_length=100)),
                ('Phone_Num', models.IntegerField()),
                ('Nationality', models.CharField(max_length=100)),
                ('Car_License', models.CharField(choices=[('Yes', 'نعم'), ('No', 'لا')], default='No', max_length=3)),
                ('Have_Car', models.CharField(choices=[('Yes', 'نعم'), ('No', 'لا')], default='No', max_length=3)),
                ('Last_Job_Desc', models.TextField(max_length=5000)),
                ('Current_Salary', models.IntegerField(blank=True, null=True)),
                ('Expected_Salary', models.IntegerField(blank=True, null=True)),
                ('Available_Date', models.DateField(default=datetime.datetime.now)),
                ('Relative_Frinds', models.CharField(choices=[('Yes', 'نعم'), ('No', 'لا')], default='No', max_length=3)),
                ('Relative_Frinds_Job', models.CharField(max_length=100)),
                ('Diseases', models.CharField(choices=[('Yes', 'نعم'), ('No', 'لا')], default='No', max_length=3)),
                ('Black_List', models.BooleanField(blank=True, default=False)),
                ('First_Approval', models.BooleanField(blank=True, default=False)),
                ('First_Approval_Note', models.TextField(blank=True, max_length=5000)),
                ('Second_Approval', models.BooleanField(blank=True, default=False)),
                ('Second_Approval_Note', models.TextField(blank=True, max_length=5000)),
                ('Coworker_Ask', models.CharField(choices=[('Yes', 'نعم'), ('No', 'لا')], default='No', max_length=3)),
                ('resume', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Duration_From', models.DateField(default=datetime.datetime.now)),
                ('Duration_To', models.DateField(default=datetime.datetime.now)),
                ('Location', models.CharField(blank=True, max_length=100, null=True)),
                ('Institute', models.CharField(max_length=100)),
                ('Training_Application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Training', to='application.application')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Degree', models.CharField(max_length=100)),
                ('University', models.CharField(max_length=100)),
                ('Graduation_Date', models.DateField(default=datetime.datetime.now)),
                ('Major', models.CharField(max_length=100)),
                ('Qualification_Application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Qualification', to='application.application')),
            ],
        ),
        migrations.CreateModel(
            name='Previous_Coworker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('Position', models.CharField(max_length=100)),
                ('Previous_Coworker_Application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Previous_Coworker', to='application.application')),
            ],
        ),
        migrations.CreateModel(
            name='Previous_Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('Duration_From', models.DateField(default=datetime.datetime.now)),
                ('Duration_To', models.DateField(default=datetime.datetime.now)),
                ('Position', models.CharField(max_length=100)),
                ('Start_Salary', models.IntegerField(blank=True, null=True)),
                ('Last_Salary', models.IntegerField(blank=True, null=True)),
                ('Reason', models.TextField(max_length=5000)),
                ('Maneger', models.CharField(max_length=100)),
                ('Previous_Company_Application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Previous_Company', to='application.application')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Language_Name', models.CharField(max_length=100)),
                ('Type_Conversation', models.CharField(choices=[('Beginner', 'ضعيف'), ('Intermediate', 'متوسط'), ('Advanced', 'ممتاز')], default='Beginner', max_length=12)),
                ('Type_Writing', models.CharField(choices=[('Beginner', 'ضعيف'), ('Intermediate', 'متوسط'), ('Advanced', 'ممتاز')], default='Beginner', max_length=12)),
                ('Type_Reading', models.CharField(choices=[('Beginner', 'ضعيف'), ('Intermediate', 'متوسط'), ('Advanced', 'ممتاز')], default='Beginner', max_length=12)),
                ('Language_Application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Language', to='application.application')),
            ],
        ),
        migrations.CreateModel(
            name='Computer_Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skill', models.CharField(max_length=100)),
                ('Level', models.CharField(choices=[('Beginner', 'ضعيف'), ('Intermediate', 'متوسط'), ('Advanced', 'ممتاز')], default='Beginner', max_length=12)),
                ('Computer_Skill_Application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Computer_Skill', to='application.application')),
            ],
        ),
    ]
