# Generated by Django 3.2.6 on 2022-08-02 13:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NID', models.CharField(error_messages={'required': 'Please let us know what to call you!'}, max_length=10, verbose_name='الرقم الوطني')),
                ('Email', models.EmailField(max_length=100, verbose_name='البريد الإلكتروني ')),
                ('Birth_Date', models.DateField(default=datetime.datetime.now, verbose_name='  تاريخ الميلاد')),
                ('Name', models.CharField(max_length=100, verbose_name=' الاسم')),
                ('Create_Date', models.DateField(auto_now_add=True, verbose_name=' تاريخ التقديم')),
                ('Socility_Status', models.CharField(choices=[('Married', 'متزوج'), ('Single', 'أعزب')], default='Single', max_length=10, verbose_name='الحالة الاجتماعية ')),
                ('Birth_Location', models.CharField(blank=True, max_length=100, verbose_name=' مكان الولادة')),
                ('City', models.CharField(max_length=100, verbose_name=' المدينة')),
                ('Location', models.CharField(blank=True, max_length=100, verbose_name='الموقع ')),
                ('Phone_Num', models.IntegerField(verbose_name='الخلوي ')),
                ('Nationality', models.CharField(max_length=100, verbose_name='الجنسية ')),
                ('Car_License', models.CharField(choices=[('Yes', 'نعم'), ('No', 'لا')], default='No', max_length=3, verbose_name=' هل لديك رخصة سواقة')),
                ('Have_Car', models.CharField(choices=[('Yes', 'نعم'), ('No', 'لا')], default='No', max_length=3, verbose_name=' هل تملك سيارة')),
                ('Last_Job_Desc', models.TextField(max_length=5000, verbose_name=' شرح أخر وظيفة')),
                ('Current_Salary', models.IntegerField(blank=True, null=True, verbose_name=' الراتب الحالي')),
                ('Expected_Salary', models.IntegerField(blank=True, null=True, verbose_name='الراتب المطلوب ')),
                ('Available_Date', models.DateField(default=datetime.datetime.now, verbose_name=' التاريخ الذي تستطيع الالتحاق فيه بالعمل')),
                ('Relative_Frinds', models.CharField(choices=[('Yes', 'نعم'), ('No', 'لا')], default='No', max_length=3, verbose_name='هل لديك اصدقاء او معارف يعملون او كانوا يعملون في شركة مجموعة منير سختيان   ')),
                ('Relative_Frinds_Job', models.CharField(blank=True, max_length=100, verbose_name='إذا كان الجواب نعم ما هي الوظيفة؟  ')),
                ('Diseases', models.CharField(choices=[('Yes', 'نعم'), ('No', 'لا')], default='No', max_length=3, verbose_name='هل تعاني من أي أمراض؟  ')),
                ('Black_List', models.BooleanField(blank=True, default=False, verbose_name=' القائمة السوداء ')),
                ('First_Approval', models.BooleanField(blank=True, default=False, verbose_name=' موافقة الموارد البشرية ')),
                ('First_Approval_Note', models.TextField(blank=True, max_length=5000, verbose_name=' ملاحظات الموارد البشرية ')),
                ('Second_Approval', models.BooleanField(blank=True, default=False, verbose_name='موافقة رئيس القسم ')),
                ('Second_Approval_Note', models.TextField(blank=True, max_length=5000, verbose_name=' ملاحظات رئيس القسم')),
                ('Coworker_Ask', models.CharField(choices=[('Yes', 'نعم'), ('No', 'لا')], default='No', max_length=3, verbose_name=' هل لديك مانع من سؤال المعرفين أو أصحاب العمل السابقين عنك ؟  ')),
                ('Interview_Date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name=' تحديد تاريخ المقابلة')),
                ('HR_Interview_Approval', models.BooleanField(default=False, verbose_name=' موافقة الموارد البشرية لتاريخ المقابلة ')),
                ('Warranty', models.CharField(choices=[('Yes', 'نعم'), ('No', 'لا')], default='No', max_length=3, null=True, verbose_name=' هل يمكنك إحضار كفالة عدلية ')),
                ('Experience_Years', models.IntegerField(verbose_name='عدد سنوات الخبرة')),
                ('Waiting_List', models.BooleanField(blank=True, default=False, verbose_name='قائمة ألإنتظار ')),
                ('resume', models.FileField(upload_to='documents/', verbose_name='السيرة الذاتية ')),
            ],
            options={
                'verbose_name': 'طلبات التوظيف',
                'verbose_name_plural': 'طلبات التوظيف',
            },
        ),
        migrations.CreateModel(
            name='Application_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NID', models.CharField(error_messages={'required': 'Please let us know what to call you!'}, max_length=10, verbose_name='الرقم الوطني')),
                ('Email', models.EmailField(max_length=100, verbose_name='البريد الإلكتروني ')),
                ('Birth_Date', models.DateField(default=datetime.datetime.now, verbose_name='  تاريخ الميلاد')),
                ('Name', models.CharField(max_length=100, verbose_name=' الاسم')),
                ('Create_Date', models.DateField(auto_now_add=True, verbose_name=' تاريخ التقديم')),
                ('Socility_Status', models.CharField(choices=[('Married', 'متزوج'), ('Single', 'أعزب')], default='Single', max_length=10, verbose_name='الحالة الاجتماعية ')),
                ('Birth_Location', models.CharField(blank=True, max_length=100, verbose_name=' مكان الولادة')),
                ('City', models.CharField(max_length=100, verbose_name=' المدينة')),
                ('Location', models.CharField(blank=True, max_length=100, verbose_name='الموقع ')),
                ('Phone_Num', models.IntegerField(verbose_name='الخلوي ')),
                ('Nationality', models.CharField(max_length=100, verbose_name='الجنسية ')),
                ('Car_License', models.CharField(choices=[('Yes', 'نعم'), ('No', 'لا')], default='No', max_length=3, verbose_name=' هل لديك رخصة سواقة')),
                ('Have_Car', models.CharField(choices=[('Yes', 'نعم'), ('No', 'لا')], default='No', max_length=3, verbose_name=' هل تملك سيارة')),
                ('Last_Job_Desc', models.TextField(max_length=5000, verbose_name=' شرح أخر وظيفة')),
                ('Current_Salary', models.IntegerField(blank=True, null=True, verbose_name=' الراتب الحالي')),
                ('Expected_Salary', models.IntegerField(blank=True, null=True, verbose_name='الراتب المطلوب ')),
                ('Available_Date', models.DateField(default=datetime.datetime.now, verbose_name=' التاريخ الذي تستطيع الالتحاق فيه بالعمل')),
                ('Relative_Frinds', models.CharField(choices=[('Yes', 'نعم'), ('No', 'لا')], default='No', max_length=3, verbose_name='هل لديك اصدقاء او معارف يعملون او كانوا يعملون في شركة مجموعة منير سختيان   ')),
                ('Relative_Frinds_Job', models.CharField(blank=True, max_length=100, verbose_name='إذا كان الجواب نعم ما هي الوظيفة؟  ')),
                ('Diseases', models.CharField(choices=[('Yes', 'نعم'), ('No', 'لا')], default='No', max_length=3, verbose_name='هل تعاني من أي أمراض؟  ')),
                ('Black_List', models.BooleanField(blank=True, default=False, verbose_name=' القائمة السوداء ')),
                ('First_Approval', models.BooleanField(blank=True, default=False, verbose_name=' موافقة الموارد البشرية ')),
                ('First_Approval_Note', models.TextField(blank=True, max_length=5000, verbose_name=' ملاحظات الموارد البشرية ')),
                ('Second_Approval', models.BooleanField(blank=True, default=False, verbose_name='موافقة رئيس القسم ')),
                ('Second_Approval_Note', models.TextField(blank=True, max_length=5000, verbose_name=' ملاحظات رئيس القسم')),
                ('Coworker_Ask', models.CharField(choices=[('Yes', 'نعم'), ('No', 'لا')], default='No', max_length=3, verbose_name=' هل لديك مانع من سؤال المعرفين أو أصحاب العمل السابقين عنك ؟  ')),
                ('Interview_Date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name=' تحديد تاريخ المقابلة')),
                ('HR_Interview_Approval', models.BooleanField(default=False, verbose_name=' موافقة الموارد البشرية لتاريخ المقابلة ')),
                ('Warranty', models.CharField(blank=True, choices=[('Yes', 'نعم'), ('No', 'لا')], default='No', max_length=3, null=True, verbose_name=' هل يمكنك إحضار كفالة عدلية')),
                ('Experience_Years', models.IntegerField(verbose_name='عدد سنوات الخبرة')),
                ('Waiting_List', models.BooleanField(blank=True, default=False, verbose_name='قائمة ألإنتظار ')),
                ('resume', models.FileField(upload_to='documents/', verbose_name='السيرة الذاتية ')),
            ],
            options={
                'verbose_name': ' طلبات التوظيف العشوائية',
                'verbose_name_plural': 'طلبات التوظيف العشوائية',
            },
        ),
        migrations.CreateModel(
            name='Computer_Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skill', models.CharField(max_length=100, verbose_name=' برنامج الحاسوب')),
                ('Level', models.CharField(choices=[('Beginner', 'ضعيف'), ('Intermediate', 'متوسط'), ('Advanced', 'ممتاز')], default='Beginner', max_length=12, verbose_name=' المهارة')),
            ],
            options={
                'verbose_name': 'مهارات الحاسوب ',
                'verbose_name_plural': 'مهارات الحاسوب ',
            },
        ),
        migrations.CreateModel(
            name='Computer_Skill_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skill', models.CharField(max_length=100, verbose_name=' برنامج الحاسوب')),
                ('Level', models.CharField(choices=[('Beginner', 'ضعيف'), ('Intermediate', 'متوسط'), ('Advanced', 'ممتاز')], default='Beginner', max_length=12, verbose_name=' المهارة')),
            ],
            options={
                'verbose_name': 'مهارات الحاسوب ',
                'verbose_name_plural': 'مهارات الحاسوب ',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_Conversation', models.CharField(choices=[('Beginner', 'ضعيف'), ('Intermediate', 'متوسط'), ('Advanced', 'ممتاز')], default='Beginner', max_length=12, verbose_name=' محادثة')),
                ('Type_Writing', models.CharField(choices=[('Beginner', 'ضعيف'), ('Intermediate', 'متوسط'), ('Advanced', 'ممتاز')], default='Beginner', max_length=12, verbose_name=' كتابة')),
                ('Type_Reading', models.CharField(choices=[('Beginner', 'ضعيف'), ('Intermediate', 'متوسط'), ('Advanced', 'ممتاز')], default='Beginner', max_length=12, verbose_name=' قراءة')),
            ],
            options={
                'verbose_name': 'اللغات ',
                'verbose_name_plural': 'اللغات ',
            },
        ),
        migrations.CreateModel(
            name='License_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name=' فئة الرخصة')),
            ],
            options={
                'verbose_name': 'فئة الرخصة ',
                'verbose_name_plural': 'فئة الرخصة ',
            },
        ),
        migrations.CreateModel(
            name='Training_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='اسم الدورة التدريبية ')),
                ('Duration_From', models.DateField(default=datetime.datetime.now, verbose_name=' تاريخ بدء الدورة')),
                ('Duration_To', models.DateField(default=datetime.datetime.now, verbose_name='تاريخ الانتهاء ')),
                ('Location', models.CharField(blank=True, max_length=100, null=True, verbose_name=' مكان انعقاد الدورة')),
                ('Institute', models.CharField(max_length=100, verbose_name='الجهة التدريبية ')),
                ('Training_Application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Training', to='application.application_form', verbose_name=' الدورات التدريبية')),
            ],
            options={
                'verbose_name': ' الدورات التدريبية  ',
                'verbose_name_plural': ' الدورات التدريبية  ',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='اسم الدورة التدريبية ')),
                ('Duration_From', models.DateField(default=datetime.datetime.now, verbose_name=' تاريخ بدء الدورة')),
                ('Duration_To', models.DateField(default=datetime.datetime.now, verbose_name='تاريخ الانتهاء ')),
                ('Location', models.CharField(blank=True, max_length=100, null=True, verbose_name=' مكان انعقاد الدورة')),
                ('Institute', models.CharField(max_length=100, verbose_name='الجهة التدريبية ')),
                ('Training_Application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Training', to='application.application', verbose_name=' الدورات التدريبية')),
            ],
            options={
                'verbose_name': ' الدورات التدريبية  ',
                'verbose_name_plural': ' الدورات التدريبية  ',
            },
        ),
        migrations.CreateModel(
            name='Qualification_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Degree', models.CharField(max_length=100, verbose_name=' المؤهل العلمي')),
                ('University', models.CharField(max_length=100, verbose_name=' اسم الجامعة')),
                ('Graduation_Date', models.DateField(default=datetime.datetime.now, verbose_name='تاريخ التخرج ')),
                ('Major', models.CharField(max_length=100, verbose_name='التخصص ')),
                ('Qualification_Application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Qualification', to='application.application_form', verbose_name=' المؤهلات الأكاديمية ')),
            ],
            options={
                'verbose_name': 'المؤهلات الأكاديمية ',
                'verbose_name_plural': 'المؤهلات الأكاديمية ',
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Degree', models.CharField(max_length=100, verbose_name=' المؤهل العلمي')),
                ('University', models.CharField(max_length=100, verbose_name=' اسم الجامعة')),
                ('Graduation_Date', models.DateField(default=datetime.datetime.now, verbose_name='تاريخ التخرج ')),
                ('Major', models.CharField(max_length=100, verbose_name='التخصص ')),
                ('Qualification_Application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Qualification', to='application.application', verbose_name=' المؤهلات الأكاديمية ')),
            ],
            options={
                'verbose_name': 'المؤهلات الأكاديمية ',
                'verbose_name_plural': 'المؤهلات الأكاديمية ',
            },
        ),
        migrations.CreateModel(
            name='Previous_Coworker_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='الاسم ')),
                ('Address', models.CharField(max_length=100, verbose_name='مكان العمل ')),
                ('Phone', models.IntegerField(blank=True, null=True, verbose_name='رقم الهاتف ')),
                ('Position', models.CharField(max_length=100, verbose_name='المسمى الوظيفي ')),
                ('Previous_Coworker_Application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Previous_Coworker', to='application.application_form', verbose_name=' المعرفين')),
            ],
            options={
                'verbose_name': 'المعرفين  ',
                'verbose_name_plural': 'المعرفين  ',
            },
        ),
        migrations.CreateModel(
            name='Previous_Coworker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='الاسم ')),
                ('Address', models.CharField(max_length=100, verbose_name='مكان العمل ')),
                ('Phone', models.IntegerField(blank=True, null=True, verbose_name='رقم الهاتف ')),
                ('Position', models.CharField(max_length=100, verbose_name='المسمى الوظيفي ')),
                ('Previous_Coworker_Application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Previous_Coworker', to='application.application', verbose_name=' المعرفين')),
            ],
            options={
                'verbose_name': 'المعرفين  ',
                'verbose_name_plural': 'المعرفين  ',
            },
        ),
        migrations.CreateModel(
            name='Previous_Company_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name=' إسم الشركة السابقة')),
                ('Address', models.CharField(max_length=100, verbose_name=' عنوان الشركة')),
                ('Phone', models.IntegerField(blank=True, null=True, verbose_name=' رقم هاتف الشركة')),
                ('Duration_From', models.DateField(default=datetime.datetime.now, verbose_name=' تاريخ بدءالعمل ')),
                ('Duration_To', models.DateField(default=datetime.datetime.now, verbose_name=' تاريخ إنتهاء العمل')),
                ('Position', models.CharField(max_length=100, verbose_name=' المسمى الوظيفي')),
                ('Start_Salary', models.IntegerField(blank=True, null=True, verbose_name=' الراتب عند البداية')),
                ('Last_Salary', models.IntegerField(blank=True, null=True, verbose_name='الراتب عند النهاية ')),
                ('Reason', models.TextField(max_length=5000, verbose_name='سبب ترك العمل ')),
                ('Maneger', models.CharField(max_length=100, verbose_name=' المدير المباشر ')),
                ('Previous_Company_Application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Previous_Company', to='application.application_form', verbose_name=' السجل الوظيفي')),
            ],
            options={
                'verbose_name': 'السجل الوظيفي  ',
                'verbose_name_plural': 'السجل الوظيفي  ',
            },
        ),
        migrations.CreateModel(
            name='Previous_Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name=' إسم الشركة السابقة')),
                ('Address', models.CharField(max_length=100, verbose_name=' عنوان الشركة')),
                ('Phone', models.IntegerField(blank=True, null=True, verbose_name=' رقم هاتف الشركة')),
                ('Duration_From', models.DateField(default=datetime.datetime.now, verbose_name=' تاريخ بدءالعمل ')),
                ('Duration_To', models.DateField(default=datetime.datetime.now, verbose_name=' تاريخ إنتهاء العمل')),
                ('Position', models.CharField(max_length=100, verbose_name=' المسمى الوظيفي')),
                ('Start_Salary', models.IntegerField(blank=True, null=True, verbose_name=' الراتب عند البداية')),
                ('Last_Salary', models.IntegerField(blank=True, null=True, verbose_name='الراتب عند النهاية ')),
                ('Reason', models.TextField(max_length=5000, verbose_name='سبب ترك العمل ')),
                ('Maneger', models.CharField(max_length=100, verbose_name=' المدير المباشر ')),
                ('Previous_Company_Application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Previous_Company', to='application.application', verbose_name=' السجل الوظيفي')),
            ],
            options={
                'verbose_name': 'السجل الوظيفي  ',
                'verbose_name_plural': 'السجل الوظيفي  ',
            },
        ),
        migrations.CreateModel(
            name='Language_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_Conversation', models.CharField(choices=[('Beginner', 'ضعيف'), ('Intermediate', 'متوسط'), ('Advanced', 'ممتاز')], default='Beginner', max_length=12, verbose_name=' محادثة')),
                ('Type_Writing', models.CharField(choices=[('Beginner', 'ضعيف'), ('Intermediate', 'متوسط'), ('Advanced', 'ممتاز')], default='Beginner', max_length=12, verbose_name=' كتابة')),
                ('Type_Reading', models.CharField(choices=[('Beginner', 'ضعيف'), ('Intermediate', 'متوسط'), ('Advanced', 'ممتاز')], default='Beginner', max_length=12, verbose_name=' قراءة')),
                ('Language_Application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Language', to='application.application_form', verbose_name=' اللغات')),
            ],
            options={
                'verbose_name': 'اللغات ',
                'verbose_name_plural': 'اللغات ',
            },
        ),
    ]
