# Generated by Django 4.0.5 on 2022-06-20 15:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NID', models.CharField(error_messages={'required': 'Please let us know what to call you!'}, max_length=10, verbose_name='الرقم الوطني')),
                ('Email', models.EmailField(max_length=100)),
                ('Birth_Date', models.DateField(default=datetime.datetime.now)),
                ('Name', models.CharField(max_length=100)),
                ('Create_Date', models.DateField(auto_now_add=True)),
                ('Socility_Status', models.CharField(choices=[('Married', 'متزوج'), ('Single', 'أعزب')], default='Single', max_length=10)),
                ('Birth_Location', models.CharField(blank=True, max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Location', models.CharField(blank=True, max_length=100)),
                ('Phone_Num', models.IntegerField()),
                ('Nationality', models.CharField(max_length=100)),
                ('Car_License', models.CharField(choices=[('Yes', 'نعم'), ('No', 'لا')], default='No', max_length=3)),
                ('Have_Car', models.CharField(choices=[('Yes', 'نعم'), ('No', 'لا')], default='No', max_length=3)),
                ('Last_Job_Desc', models.TextField(max_length=5000)),
                ('Current_Salary', models.IntegerField(blank=True, default=0, null=True)),
                ('Expected_Salary', models.IntegerField(blank=True, default=0, null=True)),
                ('Available_Date', models.DateField(default=datetime.datetime.now)),
                ('Relative_Frinds', models.CharField(choices=[('Yes', 'نعم'), ('No', 'لا')], default='No', max_length=3)),
                ('Relative_Frinds_Job', models.CharField(max_length=100)),
                ('Diseases', models.CharField(choices=[('Yes', 'نعم'), ('No', 'لا')], default='No', max_length=3)),
                ('L_Language', models.CharField(max_length=100)),
                ('L_Type_Conversation', models.CharField(choices=[('Beginner', 'ضعيف'), ('Intermediate', 'متوسط'), ('Advanced', 'ممتاز')], default='Beginner', max_length=12)),
                ('L_Type_Writing', models.CharField(choices=[('Beginner', 'ضعيف'), ('Intermediate', 'متوسط'), ('Advanced', 'ممتاز')], default='Beginner', max_length=12)),
                ('L_Type_Reading', models.CharField(choices=[('Beginner', 'ضعيف'), ('Intermediate', 'متوسط'), ('Advanced', 'ممتاز')], default='Beginner', max_length=12)),
                ('C_Computer_Skill', models.CharField(max_length=100)),
                ('C_Computer_Level', models.CharField(choices=[('Beginner', 'ضعيف'), ('Intermediate', 'متوسط'), ('Advanced', 'ممتاز')], default='Beginner', max_length=12)),
                ('Company_Prev_Name', models.CharField(max_length=100)),
                ('Company_Prev_Address', models.CharField(max_length=100)),
                ('Company_Prev_Phone', models.IntegerField(blank=True, default=0, null=True)),
                ('Company_Prev_Duration_From', models.DateField(default=datetime.datetime.now)),
                ('Company_Prev_Duration_To', models.DateField(default=datetime.datetime.now)),
                ('Company_Prev_Position', models.CharField(max_length=100)),
                ('Company_Prev_Start_Salary', models.IntegerField(blank=True, default=0, null=True)),
                ('Company_Prev_Last_Salary', models.IntegerField(blank=True, default=0, null=True)),
                ('Company_Prev_Reason', models.TextField(max_length=5000)),
                ('Company_Prev_Maneger', models.CharField(max_length=100)),
                ('T_Training_Name', models.CharField(max_length=100)),
                ('T_Training_Duration_From', models.DateField(default=datetime.datetime.now)),
                ('T_Training_Duration_To', models.DateField(default=datetime.datetime.now)),
                ('T_Training_Location', models.CharField(blank=True, max_length=100, null=True)),
                ('T_Training_Institute', models.CharField(max_length=100)),
                ('Prev_Coworker_Name', models.CharField(max_length=100)),
                ('Prev_Coworker_Address', models.CharField(max_length=100)),
                ('Prev_Coworker_Phone', models.IntegerField(blank=True, default=0, null=True)),
                ('Prev_Coworker_Position', models.CharField(max_length=100)),
                ('Coworker_Ask', models.CharField(choices=[('Yes', 'نعم'), ('No', 'لا')], default='No', max_length=3)),
                ('Black_List', models.BooleanField(blank=True, default=False)),
                ('First_Approval', models.BooleanField(blank=True, default=False)),
                ('First_Approval_Note', models.TextField(blank=True, max_length=5000)),
                ('Second_Approval', models.BooleanField(blank=True, default=False)),
                ('Second_Approval_Note', models.TextField(blank=True, max_length=5000)),
                ('Job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.job')),
            ],
        ),
    ]
