# Generated by Django 3.2.6 on 2022-06-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(default=1, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
