# Generated by Django 3.2.6 on 2022-06-26 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_application_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='Job',
            new_name='Job_App',
        ),
    ]
