# Generated by Django 3.2.6 on 2022-08-08 10:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_job_expiration_date'),
        ('application', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computer_skill_form',
            options={'verbose_name': 'مهارات الحاسوب', 'verbose_name_plural': 'مهارات الحاسوب'},
        ),
        migrations.AlterModelOptions(
            name='qualification_form',
            options={'verbose_name': 'المؤهلات الأكاديمية', 'verbose_name_plural': 'المؤهلات الأكاديمية'},
        ),
        migrations.AlterField(
            model_name='computer_skill',
            name='Computer_Skill_Application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Computer_Skill', to='application.application', verbose_name='برامج الحاسوب'),
        ),
        migrations.AlterField(
            model_name='computer_skill',
            name='Level',
            field=models.CharField(choices=[('Beginner', 'ضعيف'), ('Intermediate', 'متوسط'), ('Advanced', 'ممتاز')], default='Beginner', max_length=12, verbose_name='المهارة'),
        ),
        migrations.AlterField(
            model_name='computer_skill_form',
            name='Computer_Skill_Application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Computer_Skill', to='application.application_form', verbose_name='برامج الحاسوب'),
        ),
        migrations.AlterField(
            model_name='computer_skill_form',
            name='Level',
            field=models.CharField(choices=[('Beginner', 'ضعيف'), ('Intermediate', 'متوسط'), ('Advanced', 'ممتاز')], default='Beginner', max_length=12, verbose_name='المهارة'),
        ),
        migrations.AlterField(
            model_name='computer_skill_form',
            name='Skill',
            field=models.CharField(max_length=100, verbose_name='برنامج الحاسوب'),
        ),
        migrations.AlterField(
            model_name='language',
            name='Language_Application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Language', to='application.application', verbose_name='اللغات'),
        ),
        migrations.AlterField(
            model_name='language',
            name='Type_Conversation',
            field=models.CharField(choices=[('Beginner', 'ضعيف'), ('Intermediate', 'متوسط'), ('Advanced', 'ممتاز')], default='Beginner', max_length=12, verbose_name='محادثة'),
        ),
        migrations.AlterField(
            model_name='language',
            name='Type_Reading',
            field=models.CharField(choices=[('Beginner', 'ضعيف'), ('Intermediate', 'متوسط'), ('Advanced', 'ممتاز')], default='Beginner', max_length=12, verbose_name='قراءة'),
        ),
        migrations.AlterField(
            model_name='language_form',
            name='Language_Application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Language', to='application.application_form', verbose_name='اللغات'),
        ),
        migrations.AlterField(
            model_name='language_form',
            name='Language_Name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.language', verbose_name='اللغة'),
        ),
        migrations.AlterField(
            model_name='language_form',
            name='Type_Conversation',
            field=models.CharField(choices=[('Beginner', 'ضعيف'), ('Intermediate', 'متوسط'), ('Advanced', 'ممتاز')], default='Beginner', max_length=12, verbose_name='محادثة'),
        ),
        migrations.AlterField(
            model_name='language_form',
            name='Type_Reading',
            field=models.CharField(choices=[('Beginner', 'ضعيف'), ('Intermediate', 'متوسط'), ('Advanced', 'ممتاز')], default='Beginner', max_length=12, verbose_name='قراءة'),
        ),
        migrations.AlterField(
            model_name='language_form',
            name='Type_Writing',
            field=models.CharField(choices=[('Beginner', 'ضعيف'), ('Intermediate', 'متوسط'), ('Advanced', 'ممتاز')], default='Beginner', max_length=12, verbose_name='كتابة'),
        ),
        migrations.AlterField(
            model_name='previous_company',
            name='Previous_Company_Application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Previous_Company', to='application.application', verbose_name='السجل الوظيفي'),
        ),
        migrations.AlterField(
            model_name='previous_company_form',
            name='Address',
            field=models.CharField(max_length=100, verbose_name='عنوان الشركة'),
        ),
        migrations.AlterField(
            model_name='previous_company_form',
            name='Duration_From',
            field=models.DateField(default=datetime.datetime.now, verbose_name='تاريخ بدءالعمل '),
        ),
        migrations.AlterField(
            model_name='previous_company_form',
            name='Duration_To',
            field=models.DateField(default=datetime.datetime.now, verbose_name='تاريخ إنتهاء العمل'),
        ),
        migrations.AlterField(
            model_name='previous_company_form',
            name='Last_Salary',
            field=models.IntegerField(blank=True, null=True, verbose_name='الراتب عند النهاية'),
        ),
        migrations.AlterField(
            model_name='previous_company_form',
            name='Maneger',
            field=models.CharField(max_length=100, verbose_name='المدير المباشر '),
        ),
        migrations.AlterField(
            model_name='previous_company_form',
            name='Name',
            field=models.CharField(max_length=100, verbose_name='إسم الشركة السابقة'),
        ),
        migrations.AlterField(
            model_name='previous_company_form',
            name='Phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='رقم هاتف الشركة'),
        ),
        migrations.AlterField(
            model_name='previous_company_form',
            name='Position',
            field=models.CharField(max_length=100, verbose_name='المسمى الوظيفي'),
        ),
        migrations.AlterField(
            model_name='previous_company_form',
            name='Previous_Company_Application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Previous_Company', to='application.application_form', verbose_name='السجل الوظيفي'),
        ),
        migrations.AlterField(
            model_name='previous_company_form',
            name='Start_Salary',
            field=models.IntegerField(blank=True, null=True, verbose_name='الراتب عند البداية'),
        ),
        migrations.AlterField(
            model_name='previous_coworker',
            name='Position',
            field=models.CharField(max_length=100, verbose_name='المسمى الوظيفي'),
        ),
        migrations.AlterField(
            model_name='previous_coworker',
            name='Previous_Coworker_Application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Previous_Coworker', to='application.application', verbose_name='المعرفين'),
        ),
        migrations.AlterField(
            model_name='previous_coworker_form',
            name='Address',
            field=models.CharField(max_length=100, verbose_name='مكان العمل'),
        ),
        migrations.AlterField(
            model_name='previous_coworker_form',
            name='Name',
            field=models.CharField(max_length=100, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='previous_coworker_form',
            name='Phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='previous_coworker_form',
            name='Position',
            field=models.CharField(max_length=100, verbose_name='المسمى الوظيفي'),
        ),
        migrations.AlterField(
            model_name='previous_coworker_form',
            name='Previous_Coworker_Application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Previous_Coworker', to='application.application_form', verbose_name='المعرفين'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='Graduation_Date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='تاريخ التخرج'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='Qualification_Application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Qualification', to='application.application', verbose_name='المؤهلات الأكاديمية'),
        ),
        migrations.AlterField(
            model_name='qualification_form',
            name='Degree',
            field=models.CharField(max_length=100, verbose_name='المؤهل العلمي'),
        ),
        migrations.AlterField(
            model_name='qualification_form',
            name='Graduation_Date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='تاريخ التخرج'),
        ),
        migrations.AlterField(
            model_name='qualification_form',
            name='Major',
            field=models.CharField(max_length=100, verbose_name='التخصص'),
        ),
        migrations.AlterField(
            model_name='qualification_form',
            name='Qualification_Application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Qualification', to='application.application_form', verbose_name='المؤهلات الأكاديمية'),
        ),
        migrations.AlterField(
            model_name='qualification_form',
            name='University',
            field=models.CharField(max_length=100, verbose_name='اسم الجامعة'),
        ),
        migrations.AlterField(
            model_name='training',
            name='Training_Application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Training', to='application.application', verbose_name='الدورات التدريبية'),
        ),
        migrations.AlterField(
            model_name='training_form',
            name='Duration_From',
            field=models.DateField(default=datetime.datetime.now, verbose_name='تاريخ بدء الدورة'),
        ),
        migrations.AlterField(
            model_name='training_form',
            name='Institute',
            field=models.CharField(max_length=100, verbose_name='الجهة التدريبية'),
        ),
        migrations.AlterField(
            model_name='training_form',
            name='Name',
            field=models.CharField(max_length=100, verbose_name='اسم الدورة التدريبية'),
        ),
        migrations.AlterField(
            model_name='training_form',
            name='Training_Application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Training', to='application.application_form', verbose_name='الدورات التدريبية'),
        ),
    ]
