# Generated by Django 2.1.7 on 2022-06-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20220615_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='Application_Birth_Location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
