# Generated by Django 3.2.6 on 2022-07-03 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_application_job_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='HR_Interview_Approval',
            field=models.CharField(choices=[('Yes', 'نعم'), ('No', 'لا')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='application',
            name='Interview_Date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
