# Generated by Django 2.1.7 on 2022-06-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_application_application_birth_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Application_Car_License',
            field=models.CharField(choices=[('Yes', 'نعم'), ('No', 'لا')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='application',
            name='Application_Have_Car',
            field=models.CharField(choices=[('Yes', 'نعم'), ('No', 'لا')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='application',
            name='Application_Socility_Status',
            field=models.CharField(choices=[('Married', 'متزوج'), ('Single', 'أعزب')], default='Single', max_length=10),
        ),
    ]
