# Generated by Django 3.2.6 on 2022-08-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20220808_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='department',
            field=models.CharField(max_length=100, null=True, verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='application',
            name='Birth_Location',
            field=models.CharField(max_length=100, verbose_name=' مكان الولادة'),
        ),
        migrations.AlterField(
            model_name='application',
            name='Black_List',
            field=models.BooleanField(default=False, verbose_name=' القائمة السوداء '),
        ),
        migrations.AlterField(
            model_name='application',
            name='Current_Salary',
            field=models.IntegerField(null=True, verbose_name=' الراتب الحالي'),
        ),
        migrations.AlterField(
            model_name='application',
            name='Expected_Salary',
            field=models.IntegerField(null=True, verbose_name='الراتب المطلوب '),
        ),
        migrations.AlterField(
            model_name='application',
            name='First_Approval',
            field=models.BooleanField(default=False, verbose_name=' موافقة الموارد البشرية '),
        ),
        migrations.AlterField(
            model_name='application',
            name='Location',
            field=models.CharField(max_length=100, verbose_name='الموقع '),
        ),
        migrations.AlterField(
            model_name='application',
            name='Relative_Frinds_Job',
            field=models.CharField(max_length=100, verbose_name='إذا كان الجواب نعم ما هي الوظيفة؟  '),
        ),
        migrations.AlterField(
            model_name='application',
            name='Second_Approval',
            field=models.BooleanField(default=False, verbose_name='موافقة رئيس القسم '),
        ),
        migrations.AlterField(
            model_name='application',
            name='Waiting_List',
            field=models.BooleanField(default=False, verbose_name='قائمة ألإنتظار '),
        ),
        migrations.AlterField(
            model_name='application_form',
            name='Birth_Location',
            field=models.CharField(max_length=100, verbose_name=' مكان الولادة'),
        ),
        migrations.AlterField(
            model_name='application_form',
            name='Black_List',
            field=models.BooleanField(default=False, verbose_name=' القائمة السوداء '),
        ),
        migrations.AlterField(
            model_name='application_form',
            name='Current_Salary',
            field=models.IntegerField(null=True, verbose_name=' الراتب الحالي'),
        ),
        migrations.AlterField(
            model_name='application_form',
            name='Expected_Salary',
            field=models.IntegerField(null=True, verbose_name='الراتب المطلوب '),
        ),
        migrations.AlterField(
            model_name='application_form',
            name='First_Approval',
            field=models.BooleanField(default=False, verbose_name=' موافقة الموارد البشرية '),
        ),
        migrations.AlterField(
            model_name='application_form',
            name='Location',
            field=models.CharField(max_length=100, verbose_name='الموقع '),
        ),
        migrations.AlterField(
            model_name='application_form',
            name='Relative_Frinds_Job',
            field=models.CharField(max_length=100, verbose_name='إذا كان الجواب نعم ما هي الوظيفة؟  '),
        ),
        migrations.AlterField(
            model_name='application_form',
            name='Second_Approval',
            field=models.BooleanField(default=False, verbose_name='موافقة رئيس القسم '),
        ),
        migrations.AlterField(
            model_name='application_form',
            name='Waiting_List',
            field=models.BooleanField(default=False, verbose_name='قائمة ألإنتظار '),
        ),
        migrations.AlterField(
            model_name='previous_company',
            name='Last_Salary',
            field=models.IntegerField(null=True, verbose_name='الراتب عند النهاية '),
        ),
        migrations.AlterField(
            model_name='previous_company',
            name='Phone',
            field=models.IntegerField(null=True, verbose_name=' رقم هاتف الشركة'),
        ),
        migrations.AlterField(
            model_name='previous_company',
            name='Start_Salary',
            field=models.IntegerField(null=True, verbose_name=' الراتب عند البداية'),
        ),
        migrations.AlterField(
            model_name='previous_company_form',
            name='Last_Salary',
            field=models.IntegerField(null=True, verbose_name='الراتب عند النهاية'),
        ),
        migrations.AlterField(
            model_name='previous_company_form',
            name='Phone',
            field=models.IntegerField(null=True, verbose_name='رقم هاتف الشركة'),
        ),
        migrations.AlterField(
            model_name='previous_company_form',
            name='Start_Salary',
            field=models.IntegerField(null=True, verbose_name='الراتب عند البداية'),
        ),
        migrations.AlterField(
            model_name='previous_coworker',
            name='Phone',
            field=models.IntegerField(null=True, verbose_name='رقم الهاتف '),
        ),
        migrations.AlterField(
            model_name='previous_coworker_form',
            name='Phone',
            field=models.IntegerField(null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='training',
            name='Location',
            field=models.CharField(max_length=100, null=True, verbose_name=' مكان انعقاد الدورة'),
        ),
        migrations.AlterField(
            model_name='training_form',
            name='Location',
            field=models.CharField(max_length=100, null=True, verbose_name=' مكان انعقاد الدورة'),
        ),
    ]
