# Generated by Django 3.2.6 on 2022-07-05 10:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
        ('application', '0003_alter_application_interview_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'طلبات التوظيف', 'verbose_name_plural': 'طلبات التوظيف'},
        ),
        migrations.AlterModelOptions(
            name='computer_skill',
            options={'verbose_name': 'مهارات الحاسوب ', 'verbose_name_plural': 'مهارات الحاسوب '},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'اللغات ', 'verbose_name_plural': 'اللغات '},
        ),
        migrations.AlterModelOptions(
            name='previous_company',
            options={'verbose_name': 'السجل الوظيفي  ', 'verbose_name_plural': 'السجل الوظيفي  '},
        ),
        migrations.AlterModelOptions(
            name='previous_coworker',
            options={'verbose_name': 'المعرفين  ', 'verbose_name_plural': 'المعرفين  '},
        ),
        migrations.AlterModelOptions(
            name='qualification',
            options={'verbose_name': 'المؤهلات الأكاديمية ', 'verbose_name_plural': 'المؤهلات الأكاديمية '},
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'verbose_name': ' الدورات التدريبية  ', 'verbose_name_plural': ' الدورات التدريبية  '},
        ),
        migrations.AlterField(
            model_name='application',
            name='Available_Date',
            field=models.DateField(default=datetime.datetime.now, verbose_name=' التاريخ الذي تستطيع الالتحاق فيه بالعمل'),
        ),
        migrations.AlterField(
            model_name='application',
            name='Birth_Date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='  تاريخ الميلاد'),
        ),
        migrations.AlterField(
            model_name='application',
            name='Birth_Location',
            field=models.CharField(blank=True, max_length=100, verbose_name=' مكان الولادة'),
        ),
        migrations.AlterField(
            model_name='application',
            name='Black_List',
            field=models.BooleanField(blank=True, default=False, verbose_name=' القائمة السوداء '),
        ),
        migrations.AlterField(
            model_name='application',
            name='Car_License',
            field=models.CharField(choices=[('Yes', 'نعم'), ('No', 'لا')], default='No', max_length=3, verbose_name=' هل لديك رخصة سواقة'),
        ),
        migrations.AlterField(
            model_name='application',
            name='City',
            field=models.CharField(max_length=100, verbose_name=' المدينة'),
        ),
        migrations.AlterField(
            model_name='application',
            name='Coworker_Ask',
            field=models.CharField(choices=[('Yes', 'نعم'), ('No', 'لا')], default='No', max_length=3, verbose_name=' هل لديك مانع من سؤال المعرفين أو أصحاب العمل السابقين عنك ؟  '),
        ),
        migrations.AlterField(
            model_name='application',
            name='Create_Date',
            field=models.DateField(auto_now_add=True, verbose_name=' تاريخ التقديم'),
        ),
        migrations.AlterField(
            model_name='application',
            name='Current_Salary',
            field=models.IntegerField(blank=True, null=True, verbose_name=' الراتب الحالي'),
        ),
        migrations.AlterField(
            model_name='application',
            name='Diseases',
            field=models.CharField(choices=[('Yes', 'نعم'), ('No', 'لا')], default='No', max_length=3, verbose_name='هل تعاني من أي أمراض؟  '),
        ),
        migrations.AlterField(
            model_name='application',
            name='Email',
            field=models.EmailField(max_length=100, verbose_name='البريد الإلكتروني '),
        ),
        migrations.AlterField(
            model_name='application',
            name='Expected_Salary',
            field=models.IntegerField(blank=True, null=True, verbose_name='الراتب المطلوب '),
        ),
        migrations.AlterField(
            model_name='application',
            name='First_Approval',
            field=models.BooleanField(blank=True, default=False, verbose_name=' موافقة الموارد البشرية '),
        ),
        migrations.AlterField(
            model_name='application',
            name='First_Approval_Note',
            field=models.TextField(blank=True, max_length=5000, verbose_name=' ملاحظات الموارد البشرية '),
        ),
        migrations.AlterField(
            model_name='application',
            name='HR_Interview_Approval',
            field=models.BooleanField(blank=True, default=False, verbose_name=' موافقة الموارد البشرية لتاريخ المقابلة '),
        ),
        migrations.AlterField(
            model_name='application',
            name='Have_Car',
            field=models.CharField(choices=[('Yes', 'نعم'), ('No', 'لا')], default='No', max_length=3, verbose_name=' هل تملك سيارة'),
        ),
        migrations.AlterField(
            model_name='application',
            name='Interview_Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name=' تحديد تاريخ المقابلة'),
        ),
        migrations.AlterField(
            model_name='application',
            name='Job_App',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='JA', to='job.job', verbose_name=' الوظيفة'),
        ),
        migrations.AlterField(
            model_name='application',
            name='Last_Job_Desc',
            field=models.TextField(max_length=5000, verbose_name=' شرح أخر وظيفة'),
        ),
        migrations.AlterField(
            model_name='application',
            name='Location',
            field=models.CharField(blank=True, max_length=100, verbose_name='الموقع '),
        ),
        migrations.AlterField(
            model_name='application',
            name='Name',
            field=models.CharField(max_length=100, verbose_name=' الاسم'),
        ),
        migrations.AlterField(
            model_name='application',
            name='Nationality',
            field=models.CharField(max_length=100, verbose_name='الجنسية '),
        ),
        migrations.AlterField(
            model_name='application',
            name='Phone_Num',
            field=models.IntegerField(verbose_name='الخلوي '),
        ),
        migrations.AlterField(
            model_name='application',
            name='Relative_Frinds',
            field=models.CharField(choices=[('Yes', 'نعم'), ('No', 'لا')], default='No', max_length=3, verbose_name='هل لديك اصدقاء او معارف يعملون او كانوا يعملون في شركة مجموعة منير سختيان   '),
        ),
        migrations.AlterField(
            model_name='application',
            name='Relative_Frinds_Job',
            field=models.CharField(max_length=100, verbose_name='إذا كان الجواب نعم ما هي الوظيفة؟  '),
        ),
        migrations.AlterField(
            model_name='application',
            name='Second_Approval',
            field=models.BooleanField(blank=True, default=False, verbose_name='موافقة رئيس القسم '),
        ),
        migrations.AlterField(
            model_name='application',
            name='Second_Approval_Note',
            field=models.TextField(blank=True, max_length=5000, verbose_name=' ملاحظات رئيس القسم'),
        ),
        migrations.AlterField(
            model_name='application',
            name='Socility_Status',
            field=models.CharField(choices=[('Married', 'متزوج'), ('Single', 'أعزب')], default='Single', max_length=10, verbose_name='الحالة الاجتماعية '),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(upload_to='documents/', verbose_name='السيرة الذاتية '),
        ),
        migrations.AlterField(
            model_name='computer_skill',
            name='Computer_Skill_Application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Computer_Skill', to='application.application', verbose_name=' برامج الحاسوب'),
        ),
        migrations.AlterField(
            model_name='computer_skill',
            name='Level',
            field=models.CharField(choices=[('Beginner', 'ضعيف'), ('Intermediate', 'متوسط'), ('Advanced', 'ممتاز')], default='Beginner', max_length=12, verbose_name=' المهارة'),
        ),
        migrations.AlterField(
            model_name='computer_skill',
            name='Skill',
            field=models.CharField(max_length=100, verbose_name=' برنامج الحاسوب'),
        ),
        migrations.AlterField(
            model_name='language',
            name='Language_Application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Language', to='application.application', verbose_name=' اللغات'),
        ),
        migrations.AlterField(
            model_name='language',
            name='Language_Name',
            field=models.CharField(max_length=100, verbose_name=' اللغة'),
        ),
        migrations.AlterField(
            model_name='language',
            name='Type_Conversation',
            field=models.CharField(choices=[('Beginner', 'ضعيف'), ('Intermediate', 'متوسط'), ('Advanced', 'ممتاز')], default='Beginner', max_length=12, verbose_name=' محادثة'),
        ),
        migrations.AlterField(
            model_name='language',
            name='Type_Reading',
            field=models.CharField(choices=[('Beginner', 'ضعيف'), ('Intermediate', 'متوسط'), ('Advanced', 'ممتاز')], default='Beginner', max_length=12, verbose_name=' قراءة'),
        ),
        migrations.AlterField(
            model_name='language',
            name='Type_Writing',
            field=models.CharField(choices=[('Beginner', 'ضعيف'), ('Intermediate', 'متوسط'), ('Advanced', 'ممتاز')], default='Beginner', max_length=12, verbose_name=' كتابة'),
        ),
        migrations.AlterField(
            model_name='previous_company',
            name='Address',
            field=models.CharField(max_length=100, verbose_name=' عنوان الشركة'),
        ),
        migrations.AlterField(
            model_name='previous_company',
            name='Duration_From',
            field=models.DateField(default=datetime.datetime.now, verbose_name=' تاريخ بدءالعمل '),
        ),
        migrations.AlterField(
            model_name='previous_company',
            name='Duration_To',
            field=models.DateField(default=datetime.datetime.now, verbose_name=' تاريخ إنتهاء العمل'),
        ),
        migrations.AlterField(
            model_name='previous_company',
            name='Last_Salary',
            field=models.IntegerField(blank=True, null=True, verbose_name='الراتب عند النهاية '),
        ),
        migrations.AlterField(
            model_name='previous_company',
            name='Maneger',
            field=models.CharField(max_length=100, verbose_name=' المدير المباشر '),
        ),
        migrations.AlterField(
            model_name='previous_company',
            name='Name',
            field=models.CharField(max_length=100, verbose_name=' إسم الشركة السابقة'),
        ),
        migrations.AlterField(
            model_name='previous_company',
            name='Phone',
            field=models.IntegerField(blank=True, null=True, verbose_name=' رقم هاتف الشركة'),
        ),
        migrations.AlterField(
            model_name='previous_company',
            name='Position',
            field=models.CharField(max_length=100, verbose_name=' المسمى الوظيفي'),
        ),
        migrations.AlterField(
            model_name='previous_company',
            name='Previous_Company_Application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Previous_Company', to='application.application', verbose_name=' السجل الوظيفي'),
        ),
        migrations.AlterField(
            model_name='previous_company',
            name='Reason',
            field=models.TextField(max_length=5000, verbose_name='سبب ترك العمل '),
        ),
        migrations.AlterField(
            model_name='previous_company',
            name='Start_Salary',
            field=models.IntegerField(blank=True, null=True, verbose_name=' الراتب عند البداية'),
        ),
        migrations.AlterField(
            model_name='previous_coworker',
            name='Address',
            field=models.CharField(max_length=100, verbose_name='مكان العمل '),
        ),
        migrations.AlterField(
            model_name='previous_coworker',
            name='Name',
            field=models.CharField(max_length=100, verbose_name='الاسم '),
        ),
        migrations.AlterField(
            model_name='previous_coworker',
            name='Phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='رقم الهاتف '),
        ),
        migrations.AlterField(
            model_name='previous_coworker',
            name='Position',
            field=models.CharField(max_length=100, verbose_name='المسمى الوظيفي '),
        ),
        migrations.AlterField(
            model_name='previous_coworker',
            name='Previous_Coworker_Application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Previous_Coworker', to='application.application', verbose_name=' المعرفين'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='Degree',
            field=models.CharField(max_length=100, verbose_name=' المؤهل العلمي'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='Graduation_Date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='تاريخ التخرج '),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='Major',
            field=models.CharField(max_length=100, verbose_name='التخصص '),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='Qualification_Application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Qualification', to='application.application', verbose_name=' المؤهلات الأكاديمية '),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='University',
            field=models.CharField(max_length=100, verbose_name=' اسم الجامعة'),
        ),
        migrations.AlterField(
            model_name='training',
            name='Duration_From',
            field=models.DateField(default=datetime.datetime.now, verbose_name=' تاريخ بدء الدورة'),
        ),
        migrations.AlterField(
            model_name='training',
            name='Duration_To',
            field=models.DateField(default=datetime.datetime.now, verbose_name='تاريخ الانتهاء '),
        ),
        migrations.AlterField(
            model_name='training',
            name='Institute',
            field=models.CharField(max_length=100, verbose_name='الجهة التدريبية '),
        ),
        migrations.AlterField(
            model_name='training',
            name='Location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=' مكان انعقاد الدورة'),
        ),
        migrations.AlterField(
            model_name='training',
            name='Name',
            field=models.CharField(max_length=100, verbose_name='اسم الدورة التدريبية '),
        ),
        migrations.AlterField(
            model_name='training',
            name='Training_Application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Training', to='application.application', verbose_name=' الدورات التدريبية'),
        ),
    ]
