# Generated by Django 3.2.6 on 2022-08-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20220814_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='القسم'),
        ),
    ]
