# Generated by Django 3.2.6 on 2022-07-05 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_career_level_language_request_job'),
        ('application', '0004_auto_20220705_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='Language_Name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.language', verbose_name='اللغة '),
        ),
    ]
