# Generated by Django 3.2.6 on 2022-06-26 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_application_job_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Degree', models.CharField(max_length=100)),
                ('University', models.CharField(max_length=100)),
                ('Graduation_Date', models.DateField()),
                ('Major', models.CharField(max_length=100)),
                ('Qualification_Application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Qualification', to='application.application')),
            ],
        ),
    ]
