# Generated by Django 2.1.7 on 2022-06-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20220615_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Application_NID',
            field=models.CharField(error_messages={'required': 'Please let us know what to call you!'}, max_length=10, verbose_name='الرقم الوطني'),
        ),
    ]
