# Generated by Django 3.2.6 on 2022-06-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Company_Prev_Last_Salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='Company_Prev_Phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='Company_Prev_Start_Salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='Current_Salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='Expected_Salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='Prev_Coworker_Phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
