# Generated by Django 4.0.5 on 2022-06-16 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20220616_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qualification_Degree', models.CharField(max_length=100)),
                ('Qualification_University', models.CharField(max_length=100)),
                ('Qualification_Graduation_Date', models.DateField(blank=True, default=0, null=True)),
                ('Qualification_Major', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='Application_Q_Degree',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Application_Q_Graduation_Date',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Application_Q_Major',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Application_Q_University',
        ),
        migrations.CreateModel(
            name='Application_Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Application_Qualification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.qualification')),
                ('Application_Qualification_Application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.application')),
            ],
        ),
    ]
