# Generated by Django 3.2.6 on 2022-08-30 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20220829_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Interview_Date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name=' تحديد تاريخ المقابلة'),
        ),
        migrations.AlterField(
            model_name='application_form',
            name='Interview_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name=' تحديد تاريخ المقابلة'),
        ),
    ]
