# Generated by Django 4.0.5 on 2022-06-16 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_qualification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='Application_Qualification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Application_Qualification2', to='application.qualification'),
        ),
        migrations.DeleteModel(
            name='Application_Qualification',
        ),
    ]
