# Generated by Django 3.2.6 on 2022-06-28 11:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20220627_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer_Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skill', models.CharField(max_length=100)),
                ('Level', models.CharField(choices=[('Beginner', 'ضعيف'), ('Intermediate', 'متوسط'), ('Advanced', 'ممتاز')], default='Beginner', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Previous_Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('Duration_From', models.DateField(default=datetime.datetime.now)),
                ('Duration_To', models.DateField(default=datetime.datetime.now)),
                ('Position', models.CharField(max_length=100)),
                ('Start_Salary', models.IntegerField(blank=True, null=True)),
                ('Last_Salary', models.IntegerField(blank=True, null=True)),
                ('Reason', models.TextField(max_length=5000)),
                ('Maneger', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Previous_Coworker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('Position', models.CharField(max_length=100)),
                ('Ask', models.CharField(choices=[('Yes', 'نعم'), ('No', 'لا')], default='No', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Duration_From', models.DateField(default=datetime.datetime.now)),
                ('Duration_To', models.DateField(default=datetime.datetime.now)),
                ('Location', models.CharField(blank=True, max_length=100, null=True)),
                ('Institute', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='C_Computer_Level',
        ),
        migrations.RemoveField(
            model_name='application',
            name='C_Computer_Skill',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Company_Prev_Address',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Company_Prev_Duration_From',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Company_Prev_Duration_To',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Company_Prev_Last_Salary',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Company_Prev_Maneger',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Company_Prev_Name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Company_Prev_Phone',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Company_Prev_Position',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Company_Prev_Reason',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Company_Prev_Start_Salary',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Coworker_Ask',
        ),
        migrations.RemoveField(
            model_name='application',
            name='L_Language',
        ),
        migrations.RemoveField(
            model_name='application',
            name='L_Type_Conversation',
        ),
        migrations.RemoveField(
            model_name='application',
            name='L_Type_Reading',
        ),
        migrations.RemoveField(
            model_name='application',
            name='L_Type_Writing',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Prev_Coworker_Address',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Prev_Coworker_Name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Prev_Coworker_Phone',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Prev_Coworker_Position',
        ),
        migrations.RemoveField(
            model_name='application',
            name='T_Training_Duration_From',
        ),
        migrations.RemoveField(
            model_name='application',
            name='T_Training_Duration_To',
        ),
        migrations.RemoveField(
            model_name='application',
            name='T_Training_Institute',
        ),
        migrations.RemoveField(
            model_name='application',
            name='T_Training_Location',
        ),
        migrations.RemoveField(
            model_name='application',
            name='T_Training_Name',
        ),
        migrations.AlterField(
            model_name='qualification',
            name='Graduation_Date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Language_Name', models.CharField(max_length=100)),
                ('Type_Conversation', models.CharField(choices=[('Beginner', 'ضعيف'), ('Intermediate', 'متوسط'), ('Advanced', 'ممتاز')], default='Beginner', max_length=12)),
                ('Type_Writing', models.CharField(choices=[('Beginner', 'ضعيف'), ('Intermediate', 'متوسط'), ('Advanced', 'ممتاز')], default='Beginner', max_length=12)),
                ('Type_Reading', models.CharField(choices=[('Beginner', 'ضعيف'), ('Intermediate', 'متوسط'), ('Advanced', 'ممتاز')], default='Beginner', max_length=12)),
                ('Language_Application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Language', to='application.application')),
            ],
        ),
    ]
