# Generated by Django 3.2.6 on 2022-08-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20220830_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_form',
            name='Visit',
            field=models.BooleanField(default=False, verbose_name=' تمت رؤيته '),
        ),
    ]
