# Generated by Django 3.2.6 on 2022-07-31 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_application_warranty'),
    ]

    operations = [
        migrations.CreateModel(
            name='License_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name=' فئة الرخصة')),
            ],
            options={
                'verbose_name': 'فئة الرخصة ',
                'verbose_name_plural': 'فئة الرخصة ',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='Experience_Years',
            field=models.IntegerField(default=0, verbose_name='عدد سنوات الخبرة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='Car_License_Type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.license_type', verbose_name=' فئة الرخصة'),
        ),
    ]
