# Generated by Django 4.0.5 on 2022-06-16 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_application_application_qualification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='Application_Qualification',
        ),
        migrations.AddField(
            model_name='qualification',
            name='Qualification_Application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Application_Qualification', to='application.application'),
        ),
    ]
