# Generated by Django 3.2.6 on 2022-08-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_application_form_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='Visit',
            field=models.BooleanField(default=False, verbose_name=' تمت رؤيته '),
        ),
    ]
