# Generated by Django 4.0.5 on 2022-06-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_remove_application_application_qualification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='Application_L_Level',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Application_L_Type',
        ),
        migrations.AddField(
            model_name='application',
            name='Application_L_Type_Conversation',
            field=models.CharField(choices=[('Beginner', 'ضعيف'), ('Intermediate', 'متوسط'), ('Advanced', 'ممتاز')], default='Beginner', max_length=12),
        ),
        migrations.AddField(
            model_name='application',
            name='Application_L_Type_Reading',
            field=models.CharField(choices=[('Beginner', 'ضعيف'), ('Intermediate', 'متوسط'), ('Advanced', 'ممتاز')], default='Beginner', max_length=12),
        ),
        migrations.AddField(
            model_name='application',
            name='Application_L_Type_Writing',
            field=models.CharField(choices=[('Beginner', 'ضعيف'), ('Intermediate', 'متوسط'), ('Advanced', 'ممتاز')], default='Beginner', max_length=12),
        ),
    ]
