# Generated by Django 3.2.6 on 2022-07-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20220731_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Relative_Frinds_Job',
            field=models.CharField(blank=True, max_length=100, verbose_name='إذا كان الجواب نعم ما هي الوظيفة؟  '),
        ),
    ]
