# Generated by Django 3.2.6 on 2022-06-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20220628_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previous_coworker',
            name='Ask',
        ),
        migrations.AddField(
            model_name='application',
            name='Coworker_Ask',
            field=models.CharField(choices=[('Yes', 'نعم'), ('No', 'لا')], default='No', max_length=3),
        ),
    ]
