# Generated by Django 4.0.5 on 2022-06-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_remove_application_application_l_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Application_C_Computer_Level',
            field=models.CharField(choices=[('Beginner', 'ضعيف'), ('Intermediate', 'متوسط'), ('Advanced', 'ممتاز')], default='Beginner', max_length=12),
        ),
    ]
