# Generated by Django 3.2.6 on 2022-08-31 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_application_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='Visit',
        ),
    ]
