# Generated by Django 3.2.6 on 2022-07-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_alter_application_relative_frinds_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='Waiting_List',
            field=models.BooleanField(blank=True, default=False, verbose_name='قائمة ألإنتظار '),
        ),
    ]
