# Generated by Django 4.0.5 on 2022-06-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_alter_application_application_c_computer_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='Application_T_Training_Duration',
        ),
        migrations.AddField(
            model_name='application',
            name='Application_T_Training_Duration_From',
            field=models.DateField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='Application_T_Training_Duration_To',
            field=models.DateField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='Application_Available_Date',
            field=models.DateField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='Application_T_Training_Institute',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='Application_T_Training_Location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
