# Generated by Django 4.0.5 on 2022-06-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_remove_application_application_t_training_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Application_Coworker_Ask',
            field=models.CharField(choices=[('Yes', 'نعم'), ('No', 'لا')], default='No', max_length=3),
        ),
    ]
