# Generated by Django 3.2.6 on 2022-10-05 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_application_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='User',
            new_name='UserID',
        ),
    ]
