# Generated by Django 3.2.6 on 2022-11-20 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='reason',
            field=models.TextField(max_length=3000, null=True, verbose_name=' السبب '),
        ),
        migrations.CreateModel(
            name='JobHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_date', models.DateField(auto_now_add=True, verbose_name=' تاريخ فتح الوظيفة')),
                ('close_date', models.DateField(auto_now_add=True, verbose_name=' تاريخ إغلاق الوظيفة')),
                ('vacancy', models.IntegerField(blank=True, null=True, verbose_name='الشواغر ')),
                ('reason', models.TextField(max_length=3000, null=True, verbose_name=' السبب ')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='JobHistory', to='job.job', verbose_name=' تاريخ الوظيفة ')),
            ],
            options={
                'verbose_name': ' تاريخ الوظيفة ',
                'verbose_name_plural': ' تاريخ الوظيفة ',
            },
        ),
    ]
