# Generated by Django 3.2.6 on 2022-11-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20221120_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobhistory',
            name='open_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name=' تاريخ فتح الوظيفة'),
        ),
    ]
