# Generated by Django 3.2.6 on 2022-11-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_jobhistory_open_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobhistory',
            name='days',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد الايام '),
        ),
    ]
