# Generated by Django 3.2.6 on 2022-11-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_jobhistory_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobhistory',
            name='close_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name=' تاريخ إغلاق الوظيفة'),
        ),
        migrations.AlterField(
            model_name='jobhistory',
            name='open_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name=' تاريخ فتح الوظيفة'),
        ),
    ]
