# Generated by Django 3.2.6 on 2022-12-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_auto_20221120_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(max_length=20000, verbose_name='الوصف '),
        ),
    ]
