# Generated by Django 3.2.6 on 2022-10-11 14:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='License_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name=' فئة الرخصة')),
            ],
            options={
                'verbose_name': 'فئة الرخصة ',
                'verbose_name_plural': 'فئة الرخصة ',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NID', models.CharField(error_messages={'required': 'Please let us know what to call you!'}, max_length=10, verbose_name='الرقم الوطني')),
                ('Email', models.EmailField(max_length=100, verbose_name='البريد الإلكتروني ')),
                ('Birth_Date', models.DateField(default=datetime.datetime.now, verbose_name='  تاريخ الميلاد')),
                ('Name', models.CharField(max_length=100, verbose_name=' الاسم')),
                ('Create_Date', models.DateField(auto_now_add=True, verbose_name=' تاريخ ألإنشاء')),
                ('Socility_Status', models.CharField(choices=[('Married', 'متزوج'), ('Single', 'أعزب')], default='Single', max_length=10, verbose_name='الحالة الاجتماعية ')),
                ('Birth_Location', models.CharField(max_length=100, verbose_name=' مكان الولادة')),
                ('City', models.CharField(max_length=100, verbose_name=' المدينة')),
                ('Location', models.CharField(max_length=100, verbose_name='الموقع ')),
                ('Phone_Num', models.IntegerField(verbose_name='الخلوي ')),
                ('Nationality', models.CharField(max_length=100, verbose_name='الجنسية ')),
                ('Car_License', models.CharField(choices=[('Yes', 'نعم'), ('No', 'لا')], default='No', max_length=3, verbose_name=' هل لديك رخصة سواقة')),
                ('Have_Car', models.CharField(choices=[('Yes', 'نعم'), ('No', 'لا')], default='No', max_length=3, verbose_name=' هل تملك سيارة')),
                ('Last_Job_Desc', models.TextField(max_length=5000, verbose_name=' شرح أخر وظيفة')),
                ('Current_Salary', models.IntegerField(null=True, verbose_name=' الراتب الحالي')),
                ('Expected_Salary', models.IntegerField(null=True, verbose_name='الراتب المطلوب ')),
                ('Available_Date', models.DateField(default=datetime.datetime.now, verbose_name=' التاريخ الذي تستطيع الالتحاق فيه بالعمل')),
                ('Relative_Frinds', models.CharField(choices=[('Yes', 'نعم'), ('No', 'لا')], default='No', max_length=3, verbose_name='هل لديك اصدقاء او معارف يعملون او كانوا يعملون في شركة مجموعة منير سختيان   ')),
                ('Relative_Frinds_Job', models.CharField(max_length=100, verbose_name='إذا كان الجواب نعم ما هي الوظيفة؟  ')),
                ('Diseases', models.CharField(choices=[('Yes', 'نعم'), ('No', 'لا')], default='No', max_length=3, verbose_name='هل تعاني من أي أمراض؟  ')),
                ('Coworker_Ask', models.CharField(choices=[('Yes', 'نعم'), ('No', 'لا')], default='No', max_length=3, verbose_name=' هل لديك مانع من سؤال المعرفين أو أصحاب العمل السابقين عنك ؟  ')),
                ('Warranty', models.CharField(blank=True, choices=[('Yes', 'نعم'), ('No', 'لا')], default='No', max_length=3, null=True, verbose_name=' هل يمكنك إحضار كفالة عدلية ')),
                ('Experience_Years', models.IntegerField(verbose_name='عدد سنوات الخبرة')),
                ('resume', models.FileField(upload_to='documents/', verbose_name='السيرة الذاتية ')),
                ('Car_License_Type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userprofile.license_type', verbose_name=' فئة الرخصة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': ' الملفات الشخصية',
                'verbose_name_plural': 'الملفات الشخصية',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='اسم الدورة التدريبية ')),
                ('Location', models.CharField(max_length=100, null=True, verbose_name=' مكان انعقاد الدورة')),
                ('Institute', models.CharField(max_length=100, verbose_name='الجهة التدريبية ')),
                ('Duration_From', models.DateField(default=datetime.datetime.now, verbose_name=' تاريخ بدء الدورة')),
                ('Duration_To', models.DateField(default=datetime.datetime.now, verbose_name='تاريخ الانتهاء ')),
                ('Training_Profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Training', to='userprofile.userprofile', verbose_name='الدورات التدريبية')),
            ],
            options={
                'verbose_name': ' الدورات التدريبية  ',
                'verbose_name_plural': ' الدورات التدريبية  ',
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Major', models.CharField(max_length=100, verbose_name='التخصص ')),
                ('Degree', models.CharField(max_length=100, verbose_name=' المؤهل العلمي')),
                ('University', models.CharField(max_length=100, verbose_name=' اسم الجامعة')),
                ('Graduation_Date', models.DateField(default=datetime.datetime.now, verbose_name='تاريخ التخرج')),
                ('Qualification_Profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Qualification', to='userprofile.userprofile', verbose_name='المؤهلات الأكاديمية')),
            ],
            options={
                'verbose_name': 'المؤهلات الأكاديمية ',
                'verbose_name_plural': 'المؤهلات الأكاديمية ',
            },
        ),
        migrations.CreateModel(
            name='Previous_Coworker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='الاسم ')),
                ('Address', models.CharField(max_length=100, verbose_name='مكان العمل ')),
                ('Phone', models.IntegerField(null=True, verbose_name='رقم الهاتف ')),
                ('Position', models.CharField(max_length=100, verbose_name='المسمى الوظيفي')),
                ('Previous_Coworker_Profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Previous_Coworker', to='userprofile.userprofile', verbose_name='المعرفين')),
            ],
            options={
                'verbose_name': 'المعرفين  ',
                'verbose_name_plural': 'المعرفين  ',
            },
        ),
        migrations.CreateModel(
            name='Previous_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name=' إسم الشركة السابقة')),
                ('Address', models.CharField(max_length=100, verbose_name=' عنوان الشركة')),
                ('Phone', models.IntegerField(null=True, verbose_name=' رقم هاتف الشركة')),
                ('Duration_From', models.DateField(default=datetime.datetime.now, verbose_name=' تاريخ بدءالعمل ')),
                ('Duration_To', models.DateField(default=datetime.datetime.now, verbose_name=' تاريخ إنتهاء العمل')),
                ('Position', models.CharField(max_length=100, verbose_name=' المسمى الوظيفي')),
                ('Start_Salary', models.IntegerField(null=True, verbose_name=' الراتب عند البداية')),
                ('Last_Salary', models.IntegerField(null=True, verbose_name='الراتب عند النهاية ')),
                ('Maneger', models.CharField(max_length=100, verbose_name=' المدير المباشر ')),
                ('Reason', models.TextField(max_length=5000, verbose_name='سبب ترك العمل ')),
                ('Previous_Company_Profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Previous_Company', to='userprofile.userprofile', verbose_name='السجل الوظيفي')),
            ],
            options={
                'verbose_name': 'السجل الوظيفي  ',
                'verbose_name_plural': 'السجل الوظيفي  ',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_Conversation', models.CharField(choices=[('Beginner', 'ضعيف'), ('Intermediate', 'متوسط'), ('Advanced', 'ممتاز')], default='Beginner', max_length=12, verbose_name='محادثة')),
                ('Type_Writing', models.CharField(choices=[('Beginner', 'ضعيف'), ('Intermediate', 'متوسط'), ('Advanced', 'ممتاز')], default='Beginner', max_length=12, verbose_name=' كتابة')),
                ('Type_Reading', models.CharField(choices=[('Beginner', 'ضعيف'), ('Intermediate', 'متوسط'), ('Advanced', 'ممتاز')], default='Beginner', max_length=12, verbose_name='قراءة')),
                ('Language_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.language', verbose_name='اللغة ')),
                ('Language_Profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Language', to='userprofile.userprofile', verbose_name='اللغات')),
            ],
            options={
                'verbose_name': 'اللغات ',
                'verbose_name_plural': 'اللغات ',
            },
        ),
        migrations.CreateModel(
            name='Computer_Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skill', models.CharField(max_length=100, verbose_name=' برنامج الحاسوب')),
                ('Level', models.CharField(choices=[('Beginner', 'ضعيف'), ('Intermediate', 'متوسط'), ('Advanced', 'ممتاز')], default='Beginner', max_length=12, verbose_name='المهارة')),
                ('Computer_Skill_Profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Computer_Skill', to='userprofile.userprofile', verbose_name='برامج الحاسوب')),
            ],
            options={
                'verbose_name': 'مهارات الحاسوب ',
                'verbose_name_plural': 'مهارات الحاسوب ',
            },
        ),
    ]
