# Generated by Django 3.2.6 on 2022-10-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Phone_Num',
            field=models.IntegerField(null=True, verbose_name='الخلوي '),
        ),
    ]
