# Generated by Django 3.2.6 on 2022-10-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_userprofile_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Experience_Years',
            field=models.IntegerField(null=True, verbose_name='عدد سنوات الخبرة'),
        ),
    ]
