"""
Django settings for JobApplicationSystem project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
from decouple import config
from django.core.mail import get_connection, send_mail
from django.core.mail.message import EmailMessage



# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATES_DIR = os.path.join(BASE_DIR, 'templates')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [".herokuapp.com", "localhost", "127.0.0.1",'10.0.0.127']


REST_FRAMEWORK = { 
"DEFAULT_PERMISSION_CLASSES": [
    "rest_framework.permissions.IsAuthenticated",
],

"DEFAULT_AUTHENTICATION_CLASSES": [ # new
    "rest_framework.authentication.SessionAuthentication",
    "rest_framework.authentication.TokenAuthentication",
],
"DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema", 
}

DJANGO_EASY_AUDIT_WATCH_AUTH_EVENTS = False
DJANGO_EASY_AUDIT_WATCH_REQUEST_EVENTS = False
DJANGO_EASY_AUDIT_UNREGISTERED_CLASSES_EXTRA = ['auth.user','auth.group',]



SPECTACULAR_SETTINGS = {
"TITLE": "Jobs API Project",
"DESCRIPTION": "MSG Job Board",
"VERSION": "1.0.0",
# OTHER SETTINGS
}

# Application definition

INSTALLED_APPS = [
    'rest_framework',
    "rest_framework.authtoken",
    "dj_rest_auth",
    "allauth",
    "allauth.account", 
    "allauth.socialaccount",
    "drf_spectacular",
    "dj_rest_auth.registration", 
    'admin_numeric_filter',
    'jazzmin',
    "whitenoise.runserver_nostatic",
    # Django modules
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django.contrib.sites", 
     # Local Apps
    'apps.job',
    'apps.application',
    'apps.api',
    'apps.userauth',
    'apps.userprofile',
    'apps.interview',
    #
    'django_summernote',
    'bootstrap_datepicker_plus',
    'bootstrap4',
    'admin_auto_filters',

    'crispy_forms',
    'smart_selects',
    'djangoql',
    'import_export',
    'django_admin_filter',
    'fieldsets_with_inlines',
    'django_cleanup.apps.CleanupConfig',
    'easyaudit',
    'django_seed',
    'admin_extra_buttons',

    



]

LOGIN_REDIRECT_URL = "/jobs"
LOGOUT_REDIRECT_URL = "/jobs"
LOGIN_URL = "login"

USE_DJANGO_JQUERY = True
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'easyaudit.middleware.easyaudit.EasyAuditMiddleware',

]

ROOT_URLCONF = 'JobApplicationSystem.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "django.template.context_processors.request",
            ],
        },
    },
]
SITE_ID = 1
WSGI_APPLICATION = 'JobApplicationSystem.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {

    "default": {
        "ENGINE": "mssql",
        "NAME": "JBDB",
        "USER": "sa",
        "PASSWORD":  config('SQLPASS'),
        "HOST": "localhost",
        #"HOST":  "sqlserver",
        "OPTIONS": {"driver": "ODBC Driver 17 for SQL Server", 
        },
    },



}
DATABASE_CONNECTION_POOLING = False


# Email Config

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'mail.sukhtian.com.jo'
EMAIL_USE_TLS = True
EMAIL_PORT = 587 
EMAIL_HOST_USER = 'hr@sukhtian.com.jo'
EMAIL_HOST_PASSWORD = config('EMAILPASS')
#DEFAULT_FROM_EMAIL = 'hr@sukhtian.com.jo'





# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'ar-jo'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

#USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'templates/static'),
)
STATICFILES_STORAGE ="whitenoise.storage.CompressedManifestStaticFilesStorage" # new

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = '/media/'
MEDIAFILES_DIRS = (
    os.path.join(BASE_DIR, 'media'),
)








  
# allows to load iframe from same hostname
X_FRAME_OPTIONS = "SAMEORIGIN"
SUMMERNOTE_THEME = 'bs4'

DEFAULT_AUTO_FIELD='django.db.models.AutoField' 




JAZZMIN_SETTINGS = {

"changeform_format": "collapsible",
"hide_apps": ["django_summernote",],
"hide_models": ["easyaudit.LoginEvent","easyaudit.RequestEvent"],
    "icons": {
        "Application.Application": "far fa-window-maximize",
        "Application.Application_Form": "far fa-sticky-note",
        "Application.License_Type": "fas fa-car",
        "Interview.Interview": "fas fa-people-arrows",
        "Job.Degree": "fas fa-certificate",
        "Job.Language": "fas fa-language",
        "Job.Location": "fas fa-globe-americas",
        "Job.Job": "fas fa-briefcase",
        "Job.Nature": "fas fa-laptop-house",
        "Job.Title": "fas fa-heading",
        "Job.Career_Level": "fas fa-sort-numeric-up-alt",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
    },
"site_title": "",
    
}