# Generated by Django 3.2.6 on 2022-11-01 16:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Visit', models.BooleanField(default=False, verbose_name=' تمت رؤيته ')),
                ('Waiting_List', models.BooleanField(default=False, verbose_name='قائمة ألإنتظار ')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='القسم')),
                ('Interview_Date', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name=' تحديد تاريخ المقابلة')),
                ('HR_Interview_Approval', models.BooleanField(default=False, verbose_name=' موافقة الموارد البشرية لتاريخ المقابلة ')),
                ('Black_List', models.BooleanField(default=False, verbose_name=' القائمة السوداء ')),
                ('First_Approval', models.BooleanField(default=False, verbose_name=' موافقة الموارد البشرية ')),
                ('First_Approval_Note', models.TextField(blank=True, max_length=5000, verbose_name=' ملاحظات الموارد البشرية ')),
                ('Second_Approval', models.BooleanField(default=False, verbose_name='موافقة رئيس القسم ')),
                ('Second_Approval_Note', models.TextField(blank=True, max_length=5000, verbose_name=' ملاحظات رئيس القسم')),
                ('Create_Date', models.DateField(auto_now_add=True, verbose_name=' تاريخ التقديم')),
                ('Job_App', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='JA', to='job.job', verbose_name=' الوظيفة')),
            ],
            options={
                'verbose_name': '  طلبات التوظيف',
                'verbose_name_plural': '  طلبات التوظيف',
            },
        ),
    ]
