# Generated by Django 3.2.6 on 2022-11-02 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_application_userprofile_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Interview_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name=' تحديد تاريخ المقابلة'),
        ),
    ]
