# Generated by Django 3.2.6 on 2022-11-10 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_alter_user_email'),
        ('application', '0003_alter_application_interview_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name=' القسم '),
        ),
    ]
