# Generated by Django 3.2.6 on 2022-11-10 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_alter_interview_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='Second_Interview_Time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name=' تحديد تاريخ المقابلة الثانية'),
        ),
    ]
