# Generated by Django 3.2.6 on 2022-12-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_interview_second_interview_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='hiring_Recommendation',
            field=models.CharField(choices=[('Pending', 'قيد الإنتظار'), ('Yes', 'نعم'), ('No', 'لا'), ('Waiting', 'قائمة الإنتظار'), ('Second_Interview', 'مقابلة ثانية '), ('Black_List', ' القائمة السوداء ')], default='Pending', max_length=16, verbose_name='التوصية بالتعين'),
        ),
    ]
