# Generated by Django 3.2.6 on 2022-11-01 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLanguage',
        ),
    ]
