# Generated by Django 3.2.6 on 2022-11-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_userlanguage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Position',
            field=models.CharField(max_length=100, null=True, verbose_name='المسمى الوظيفي'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Relative_Frinds_Job',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='إذا كان الجواب نعم ما هي الوظيفة؟  '),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='الصورة الشخصية'),
        ),
    ]
