# Generated by Django 3.2.6 on 2022-11-20 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_created_by'),
        ('userprofile', '0004_auto_20221109_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Profile_Job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PJ', to='job.job', verbose_name=' الوظيفة'),
        ),
        migrations.AlterField(
            model_name='userlanguage',
            name='Language_Profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='UserLanguage', to='userprofile.userprofile', verbose_name='اللغات'),
        ),
    ]
