# Generated by Django 3.2.6 on 2022-12-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20221120_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Black_List',
            field=models.BooleanField(default=False),
        ),
    ]
