# Generated by Django 3.2.6 on 2022-08-08 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='تاريخ إنتهاء الوظيفة '),
        ),
    ]
