# Generated by Django 3.2.6 on 2022-07-05 10:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
import job.enum


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': ' الوظائف ', 'verbose_name_plural': ' الوظائف '},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': ' الموقع ', 'verbose_name_plural': ' الموقع '},
        ),
        migrations.AlterModelOptions(
            name='nature',
            options={'verbose_name': ' طبيعة العمل ', 'verbose_name_plural': ' طبيعة العمل '},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': ' عنوان الوظيفة ', 'verbose_name_plural': ' عنوان الوظيفة '},
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(max_length=3000, verbose_name='الوصف '),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_max',
            field=models.IntegerField(blank=True, verbose_name='الخبرة الى '),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_min',
            field=models.IntegerField(blank=True, verbose_name='الخبرة من'),
        ),
        migrations.AlterField(
            model_name='job',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='تاريخ إنتهاء الوظيفة '),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.location', verbose_name='الموقع '),
        ),
        migrations.AlterField(
            model_name='job',
            name='nature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.nature', verbose_name='طبيعة العمل '),
        ),
        migrations.AlterField(
            model_name='job',
            name='post_date',
            field=models.DateField(auto_now_add=True, verbose_name=' تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.IntegerField(blank=True, verbose_name='الراتب '),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default=job.enum.Status['ACTIVE'], max_length=255, verbose_name='حالة الوظيفة '),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.title', verbose_name='عنوان الوظيفة '),
        ),
        migrations.AlterField(
            model_name='job',
            name='vacancy',
            field=models.IntegerField(blank=True, verbose_name='الشواغر '),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_name',
            field=models.CharField(max_length=300, verbose_name=' الموقع'),
        ),
        migrations.AlterField(
            model_name='nature',
            name='Nature_name',
            field=models.CharField(max_length=300, verbose_name=' طبيعة العمل'),
        ),
        migrations.AlterField(
            model_name='title',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name=' القسم'),
        ),
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(max_length=300, verbose_name=' عنوان الوظيفة'),
        ),
    ]
