# Generated by Django 3.2.6 on 2022-07-05 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('job', '0002_auto_20220705_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career_Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=300, verbose_name='  مستوى الخبرة')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name=' اللغة')),
            ],
        ),
        migrations.CreateModel(
            name='Request_Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_min', models.IntegerField(blank=True, verbose_name='الخبرة من')),
                ('experience_max', models.IntegerField(blank=True, verbose_name='الخبرة الى ')),
                ('Education', models.CharField(max_length=300, verbose_name='  الدرجة الجامعية')),
                ('required_competencies', models.TextField(max_length=3000, verbose_name='المهارات المطلوبة ')),
                ('other', models.TextField(max_length=3000, verbose_name=' مهارات أخرى ')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name=' القسم')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.language', verbose_name='اللغة ')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.location', verbose_name='الموقع ')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.title', verbose_name='عنوان الوظيفة ')),
            ],
            options={
                'verbose_name': ' طلب وظيفة  ',
                'verbose_name_plural': ' طلب وظيفة  ',
            },
        ),
    ]
