# Generated by Django 3.2.6 on 2022-06-29 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('job', '0002_department_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department_person',
            name='DepartmentPerson',
        ),
        migrations.AlterField(
            model_name='job',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Department_Person',
        ),
    ]
