# Generated by Django 3.2.6 on 2022-08-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_job_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='expiration_date',
            field=models.DateField(default='2022-8-8', verbose_name='تاريخ إنتهاء الوظيفة '),
        ),
    ]
