# Generated by Django 2.1.7 on 2022-06-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_job_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_post_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
