# Generated by Django 3.2.6 on 2022-06-30 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20220630_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='expiration_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
