# Generated by Django 3.2.6 on 2022-07-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_career_level_language_request_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_job',
            name='language',
        ),
        migrations.AddField(
            model_name='request_job',
            name='language',
            field=models.ManyToManyField(null=True, to='job.Language', verbose_name='اللغة '),
        ),
    ]
