# Generated by Django 2.1.7 on 2022-06-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20220612_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_post_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
