# Generated by Django 3.2.6 on 2022-07-05 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20220705_1216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='career_level',
            options={'verbose_name': 'مستوى الخبرة ', 'verbose_name_plural': ' مستوى الخبرة '},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'اللغات  ', 'verbose_name_plural': ' اللغات '},
        ),
        migrations.AddField(
            model_name='request_job',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.career_level', verbose_name='  مستوى الخبرة'),
        ),
    ]
