# Generated by Django 2.1.7 on 2022-06-13 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20220612_0736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='job_experience_max',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_experience_min',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_nature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_salary',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_vacancy',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AddField(
            model_name='job',
            name='job_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.Location'),
        ),
    ]
