# Generated by Django 3.2.6 on 2022-06-30 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20220630_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='DepartmentPerson',
            new_name='department_person',
        ),
    ]
