# Generated by Django 2.1.7 on 2022-06-13 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20220613_0628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Nature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_Nature_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='job_nature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.Job_Nature'),
        ),
    ]
