# Generated by Django 3.2.6 on 2022-08-31 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_job_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Career_Level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.career_level', verbose_name='مستوى الخبرة '),
        ),
    ]
