# Generated by Django 3.2.6 on 2022-07-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20220705_1223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='career_level',
            options={'verbose_name': 'اللغات  ', 'verbose_name_plural': ' اللغات '},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={},
        ),
        migrations.AddField(
            model_name='job',
            name='langs',
            field=models.ManyToManyField(null=True, to='job.Language', verbose_name='اللغات '),
        ),
    ]
