# Generated by Django 3.2.6 on 2022-07-20 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_auto_20220720_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='الدرجة العلمية')),
            ],
            options={
                'verbose_name': ' الدرجة العلمية',
                'verbose_name_plural': ' الدرجة العلمية ',
            },
        ),
        migrations.AlterModelOptions(
            name='career_level',
            options={'verbose_name': 'مستوى الخبرة ', 'verbose_name_plural': ' مستوى الخبرة '},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'اللغات  ', 'verbose_name_plural': ' اللغات '},
        ),
        migrations.AddField(
            model_name='job',
            name='Education',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.degree', verbose_name='الدرجة العلمية '),
        ),
        migrations.AlterField(
            model_name='request_job',
            name='Education',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.degree', verbose_name='الدرجة العلمية '),
        ),
    ]
