# Generated by Django 3.2.6 on 2022-06-30 18:08

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0006_rename_departmentperson_job_department_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='department_person',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='department', chained_model_field='department', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
