# Generated by Django 2.1.7 on 2022-06-13 08:51

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_auto_20220613_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default=job.models.Job_Status('ACTIVE'), max_length=255),
        ),
    ]
