# Generated by Django 2.1.7 on 2022-06-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_job_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_post_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
