# Generated by Django 3.2.6 on 2022-07-21 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('job', '0007_auto_20220720_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name=' القسم'),
        ),
    ]
