# Generated by Django 3.2.6 on 2022-09-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_alter_job_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ إنتهاء الوظيفة '),
        ),
    ]
