# Generated by Django 3.2.6 on 2022-06-30 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_alter_job_department_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='department_person',
        ),
    ]
