# Generated by Django 3.2.6 on 2022-07-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_job_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='warranty',
            field=models.BooleanField(blank=True, default=False, verbose_name='  هل يتطلب إحضار كفالة عدلية '),
        ),
    ]
