# Generated by Django 3.2.6 on 2022-07-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_title_warranty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='description',
        ),
        migrations.AddField(
            model_name='title',
            name='description',
            field=models.TextField(default=0, max_length=3000, verbose_name='الوصف '),
            preserve_default=False,
        ),
    ]
