# Generated by Django 3.2.6 on 2022-07-03 10:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0009_auto_20220703_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='department_person',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
