# Generated by Django 3.2.6 on 2022-07-03 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('job', '0010_title_department_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='title',
            name='department_person',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='department', chained_model_field='username', null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
