# Generated by Django 3.2.6 on 2022-07-03 10:44

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0012_alter_title_department_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='department_person',
        ),
        migrations.AddField(
            model_name='title',
            name='department_person',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='department', chained_model_field='username', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
