# Generated by Django 3.2.6 on 2022-07-03 10:46

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0013_auto_20220703_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='department_person',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='department', chained_model_field='username', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
