# Generated by Django 3.2.6 on 2022-07-03 12:51

from django.conf import settings
from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0015_auto_20220703_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='department_person',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='department', chained_model_field='groups', horizontal=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='department_person'),
        ),
    ]
