# Generated by Django 3.2.6 on 2022-07-03 16:53

from django.conf import settings
from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0016_alter_title_department_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='department_person',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='department', chained_model_field='groups', horizontal=True, null=True, related_name='usertitle', to=settings.AUTH_USER_MODEL, verbose_name='department_person'),
        ),
    ]
